Repository nextcloud/text, pull requests merged in 2019-11, with the labels that each got.

#397 Distinguish second and third-level list entries
  css/prosemirror.scss
Labels: 3. to review, design, enhancement, feature: formatting

#404 Add more top spacing to h1 and h2
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/preview.js
  js/preview.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
Labels: 3. to review, design, enhancement

#399 Fix editor stretching the file list
  src/components/EditorWrapper.vue
Labels: 3. to review, bug
