Repository nextcloud/text, pull requests merged in 2019-10, with the labels that each got.

#322 Throw proper NotFoundException if a file is not found by id
  lib/Service/DocumentService.php
Labels: 3. to review, bug

#329 Eslint global config
  .eslintrc.js
  package-lock.json
  package.json
  src/components/EditorWrapper.vue
  src/components/FilesEditor.vue
  src/components/GuestNameDialog.vue
  src/components/MenuBar.vue
  src/components/MenuBubble.vue
  src/components/PublicFilesEditor.vue
  src/components/ReadOnlyEditor.vue
  src/components/SessionList.vue
  src/helpers/files.js
  src/nodes/ImageView.vue
Labels: 3. to review, technical debt

#340 Make sure the sync service is available when trying to close
  src/components/EditorWrapper.vue
Labels: 3. to review, bug

#375 Reduce 'Removed X inactive sessions' severity to debug
  lib/Cron/Cleanup.php
Labels: 4. to release, enhancement

#379 Make sure the menububble is always refering the document container
  src/components/EditorWrapper.vue
Labels: 3. to review, bug

#384 File sidebar previews
  css/prosemirror.scss
  css/style.scss
  js/187.js
  js/187.js.map
  js/188.js
  js/188.js.map
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~files-modal.js
  js/vendors~files-modal.js.map
  src/components/EditorWrapper.vue
  src/components/ReadOnlyEditor.vue
  src/files.js
  src/files/PreviewPlugin.js
Labels: 3. to review, enhancement
