Repository nextcloud/text, pull requests merged in 2019-12, with the labels that each got.

#457 Fix Undefined variable: initialStateService
  lib/AppInfo/Application.php
Labels: 3. to review, bug

#468 Rich workspaces: Slightly reduce vertical space
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  src/views/RichWorkspace.vue
Labels: 4. to release, design, enhancement

#469 Update to use @nextcloud/browserslist-config
  package-lock.json
  package.json
Labels: 4. to release, dependencies: javascript

#451 Use file path to obtain workspace direct editing links
  lib/Controller/WorkspaceController.php
Labels: 3. to review

#473 Adjust viewer props
  js/files.js
  js/files.js.map
  src/components/FilesEditor.vue
Labels: 1. to develop, bug: regression

#477 Use file path instead of folder for direct workspace opening
  lib/Controller/WorkspaceController.php
Labels: 4. to release, bug

#478 Remove dot from direct editing file extension
  lib/DirectEditing/TextDocumentCreator.php
Labels: 3. to review, bug

#485 DoumentId should be a string when using as a filename
  lib/Service/DocumentService.php
Labels: 4. to release, bug
