Repository nextcloud/text, pull requests merged in 2019-07, with the labels that each got.

#142 Require at least 16.0.1
  appinfo/info.xml
Labels: 3. to review, bug

#141 Fix file actions fallback when viewer is disabled
  src/files.js
  src/helpers/files.js
Labels: 3. to review, bug

#148 Force proper step order
  lib/Db/StepMapper.php
Labels: 3. to review, bug

#149 Keep checkboxes as plain text
  src/EditorFactory.js
  src/tests/markdown.spec.js
Labels: 3. to review, bug

#154 Reconnect after session has timed out
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  src/EditorFactory.js
  src/components/EditorWrapper.vue
  src/public.js
  src/services/PollingBackend.js
  src/services/SyncService.js
Labels: 3. to review, bug

#155 Bump version to 1.0.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#168 Mark text app as default enabled
  .drone.yml
  appinfo/info.xml
Labels: 3. to review

#177 Add translations for menu bar and ignore js folder
  .l10nignore
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  src/components/MenuBar.vue
  src/mixins/menubar.js
Labels: 3. to review, backport-request, bug

#194 Fixed typo
  src/mixins/menubar.js
Labels: backport-request

#204 issue template typos and improvements
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: 3. to review

#200 Improve network error handling
  src/EditorFactory.js
  src/components/EditorWrapper.vue
  src/services/PollingBackend.js
  src/services/SyncService.js
Labels: 3. to review, backport-request, bug
