Repository nextcloud/text, pull requests merged in 2020-08, with the labels that each got.

#921 fix: use OC.Files API to get file info
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~files-modal.js
  js/vendors~files-modal.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/MenuBar.vue
  src/helpers/files.js
Labels: 4. to release, backport-request, bug

#879 Link to local files
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~editor~files-modal.js
  js/vendors~editor~files-modal.js.map
  js/vendors~files-modal.js
  js/vendors~files-modal.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/EditorWrapper.vue
  src/components/MenuBar.vue
  src/components/MenuBubble.vue
  src/helpers/files.js
  src/helpers/links.js
  src/marks/index.js
  src/tests/helpers/links.spec.js
  src/tests/nodes/ImageView.spec.js
Labels: 4. to release, enhancement

#970 highlight active heading in menu bar
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/MenuBar.vue
Labels: 4. to release, design: papercut

#988 Only overwrite Ctrl-f when text is focussed
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/EditorWrapper.vue
  src/extensions/Keymap.js
Labels: 3. to review, bug, bug: regression

#993 Catch StorageNotAvailable exceptions
  lib/Controller/WorkspaceController.php
  lib/DAV/WorkspacePlugin.php
  lib/Service/WorkspaceService.php
Labels: 3. to review, backport-request
