Repository nextcloud/text, pull requests merged in 2020-01, with the labels that each got.

#505 Rich workspace polishing
  css/prosemirror.scss
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/preview.js
  js/preview.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  src/components/MenuBar.vue
  src/nodes/ListItem.js
  src/views/RichWorkspace.vue
Labels: 3. to review, bug, feature: rich workspaces

#509 Add more mimetypes for plain text editing
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  src/helpers/mime.js
Labels: 3. to review, bug

#512 Fix design of menububble for adding links
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  src/components/MenuBubble.vue
Labels: 3. to review, bug, design

#526 Fix calling setLastContact on boolean
  lib/Service/SessionService.php
Labels: 3. to review, backport-request, bug

#530 [stable18] Run tests against stable18
  .drone.yml
  appinfo/info.xml
Labels: 3. to review, tests

#529 Master is 19
  appinfo/info.xml
Labels: 3. to review, tests

#508 Properly handle file deletion and temporary service unavailability
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  lib/Service/ApiService.php
  src/components/EditorWrapper.vue
  src/services/PollingBackend.js
  src/views/RichWorkspace.vue
Labels: 3. to review, backport-request, bug

#531 UI polishing
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  src/components/EditorWrapper.vue
  src/components/MenuBar.vue
  src/views/DirectEditing.vue
  src/views/RichWorkspace.vue
Labels: 3. to review, backport-request, design

#557 Fix last saved typo
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  src/components/EditorWrapper.vue
Labels: 4. to release

#568 Do not try obtaining the file by id when a share link is used
  lib/Service/DocumentService.php
Labels: 3. to review, backport-request, bug

#575 UI polishing
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  src/components/GuestNameDialog.vue
  src/components/SessionList.vue
Labels: 3. to review, backport-request, bug

#574 Move nested div from checkbox rendering
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/preview.js
  js/preview.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor~preview.js
  js/vendors~editor~preview.js.map
  src/nodes/ListItem.js
Labels: 3. to review, backport-request, bug

#577 Fix editing plain text files with direct editing
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  lib/DirectEditing/TextDirectEditor.php
  src/views/DirectEditing.vue
Labels: 3. to review, backport-request, bug

#597 Use a proper value for checking if workspaces are available
  lib/AppInfo/Application.php
Labels: backport-request

#609 Rename document creator (fixes #599)
  lib/DirectEditing/TextDocumentCreator.php
Labels: 3. to review, backport-request, enhancement

#618 Lint on github actions
  .drone.yml
  .github/workflows/lint.yml
  composer.json
Labels: 3. to review

#612 Catch the exception when a user no longer exists
  lib/Service/DocumentService.php
Labels: 4. to release, bug

#608 UI fixes for public share links
  css/style.scss
  cypress/integration/share.spec.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/preview.js
  js/preview.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  lib/Service/DocumentService.php
  src/EditorFactory.js
  src/components/EditorWrapper.vue
  src/components/MenuBar.vue
  src/nodes/ListItem.js
  src/views/DirectEditing.vue
  src/views/FilesSettings.vue
  src/views/RichWorkspace.vue
Labels: 3. to review, backport-request, bug
