Repository nextcloud/text, pull requests merged in 2020-07, with the labels that each got.

#912 Log the exceptions as INFO
  lib/Service/ApiService.php
Labels: 3. to review, enhancement

#904 Check if a file was created manually before creating a new workspace
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/views/RichWorkspace.vue
Labels: 3. to review, bug

#924 Use IBootstrap for the app bootstrap
  cypress/docker-compose.yml
  lib/AppInfo/Application.php
  lib/Listeners/FilesLoadAdditionalScriptsListener.php
  lib/Listeners/FilesSharingLoadAdditionalScriptsListener.php
  lib/Listeners/LoadViewerListener.php
  lib/Listeners/RegisterDirectEditorEventListener.php
Labels: 3. to review, technical debt

#929 Enh/noid/sharing additional scripts event
  js/public.js
  js/public.js.map
  lib/AppInfo/Application.php
  lib/Listeners/FilesSharingLoadAdditionalScriptsListener.php
  src/public.js
Labels: 3. to review, bug
