Repository nextcloud/text, pull requests merged in 2020-06, with the labels that each got.

#852 Also translate 'Add notes, ...' inside Editor
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~editor~files-modal.js
  js/vendors~editor~files-modal.js.map
  js/vendors~files-modal.js
  js/vendors~files-modal.js.map
  js/viewer.js
  js/viewer.js.map
  package-lock.json
  package.json
  src/EditorFactory.js
Labels: 4. to release, bug

#504 Allow embedding relative image paths
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~editor~files-modal.js
  js/vendors~editor~files-modal.js.map
  js/vendors~files-modal.js
  js/vendors~files-modal.js.map
  js/viewer.js
  js/viewer.js.map
  lib/Controller/WorkspaceController.php
  lib/Service/WorkspaceService.php
  src/components/EditorWrapper.vue
  src/components/MenuBar.vue
  src/nodes/ImageView.vue
  src/tests/nodes/ImageView.spec.js
Labels: 4. to release, enhancement

#855 Add proxy-polyfill to make tiptap work with IE11
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~editor~files-modal.js
  js/vendors~editor~files-modal.js.map
  js/vendors~files-modal.js
  js/vendors~files-modal.js.map
  js/viewer.js
  js/viewer.js.map
  package-lock.json
  package.json
  src/EditorFactory.js
  webpack.common.js
Labels: 3. to review, backport-request, bug

#871 Perform file conflict check earlier so that it also triggers when not saving
  lib/Service/DocumentService.php
Labels: 3. to review, backport-request, bug

#877 Don’t show empty workspace container if files are not creatable
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/views/RichWorkspace.vue
Labels: 3. to review, bug

#878 Show tooltip on link hover
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/EditorFactory.js
  src/marks/index.js
Labels: 3. to review, backport-request, bug

#888 fix: path for workspaces
  lib/Controller/WorkspaceController.php
Labels: 4. to release, bug
