Repository nextcloud/text, pull requests merged in 2020-09, with the labels that each got.

#994 only return rich workspace when depth is 1 or greater
  lib/DAV/WorkspacePlugin.php
Labels: 2. developing, backport-request, bug

#1004 Use proper event for loading scripts on public share links
  lib/AppInfo/Application.php
Labels: 3. to review, bug: regression

#1016 Harden read only check on public endpoints
  lib/Service/ApiService.php
Labels: 3. to review, backport-request

#1014 Harden check when using token from memcache
  lib/Service/SessionService.php
Labels: 3. to review, backport-request, enhancement

#1007 Move to automated dependabot merging
  .github/dependabot.yml
  .github/workflows/dependabot-approve-merge.yml
Labels: 3. to review, dependencies

#1025 Sessionid is an int
  lib/Controller/PublicSessionController.php
Labels: 3. to review, backport-request, enhancement

#1026 Refresh lastContact only once every 30 seconds
  js/editor-collab.js
  js/editor-collab.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  lib/Db/Session.php
  lib/Service/SessionService.php
  src/components/SessionList.vue
Labels: 3. to review, enhancement

#1053 Check if error is ocs response on workspace request
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/views/RichWorkspace.vue
Labels: 3. to review, enhancement

#1057 Fix images in public links
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/nodes/ImageView.vue
  src/tests/nodes/ImageView.spec.js
Labels: 3. to review, backport-request, bug, bug: regression
