Repository nextcloud/text, pull requests merged in 2020-05, with the labels that each got.

#834 Fix rich workspaces on case insensitive filesystems
  lib/Service/WorkspaceService.php
Labels: 3. to review, backport-request, bug

#832 Fix server styles causing images being to small
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
Labels: 4. to release, backport-request, bug

#809 same size for checkboxes
  css/prosemirror.scss
Labels: 4. to release, bug

#798 Handle 403 errors the same as not found
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/services/PollingBackend.js
Labels: 4. to release, backport-request, bug

#829 emit `ready` signal via parent
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/EditorWrapper.vue
Labels: 4. to release, bug
