Repository nextcloud/text, pull requests merged in 2020-03, with the labels that each got.

#672 [stable17] Avoid race condition when adding steps and fix step entries with duplicate versions
  appinfo/info.xml
  lib/Command/ResetDocument.php
  lib/Db/SessionMapper.php
  lib/Db/StepMapper.php
  lib/Service/DocumentService.php
Labels: 3. to review, bug

#695 Bugfix/noid/rich workspace empty height
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  src/views/RichWorkspace.vue
Labels: 3. to review, design: papercut

#714 Fix rich workspaces on folders without create permissions
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/preview.js
  js/preview.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~files-modal.js
  js/vendors~files-modal.js.map
  lib/AppInfo/Application.php
  lib/Controller/WorkspaceController.php
  src/public.js
  src/views/RichWorkspace.vue
Labels: 4. to release, backport-request, bug, feature: rich workspaces

#708 Use New OCA.Files.Settings API
  js/files.js
  js/files.js.map
  src/files.js
Labels: 4. to release, enhancement, technical debt
