Repository nextcloud/text, pull requests merged in 2020-11, with the labels that each got.

#1068 Do not setup appdata in constructor to avoid errors causing the whole instance to stop working
  lib/Service/DocumentService.php
Labels: 3. to review, bug

#1110 Add dependabot config for stable branches
  .github/dependabot.yml
Labels: 3. to review, dependencies: javascript

#1165 Validate link on click
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~files-modal.js
  js/vendors~files-modal.js.map
  js/viewer.js
  js/viewer.js.map
  src/marks/index.js
Labels: 3. to review, bug

#1168 [stable18] Validate link on click
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~editor~files-modal.js
  js/vendors~editor~files-modal.js.map
  src/marks/index.js
Labels: 3. to review, bug

#1167 [stable19] Validate link before opening
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~editor~files-modal.js
  js/vendors~editor~files-modal.js.map
  js/viewer.js
  js/viewer.js.map
  src/marks/index.js
Labels: 3. to review, bug

#1176 Add migration to fix oracle issues with the database schema
  .github/workflows/oci.yml
  lib/Migration/Version030201Date20201116110353.php
  lib/Migration/Version030201Date20201116123153.php
Labels: 3. to review, backport-request, bug

#1162 Disconnect session after 30 minutes of idle timeout
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/EditorWrapper.vue
  src/services/PollingBackend.js
  src/services/SyncService.js
Labels: 4. to release, enhancement, performance

#1187 Move away from GET
  appinfo/routes.php
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/services/SyncService.js
Labels: 3. to review, enhancement
