Repository nextcloud/text, pull requests merged in 2020-02, with the labels that each got.

#656 [stable18] UI fixes
  css/style.scss
  cypress/integration/share.spec.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/preview.js
  js/preview.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  lib/Service/DocumentService.php
  src/EditorFactory.js
  src/components/EditorWrapper.vue
  src/components/MenuBar.vue
  src/nodes/ListItem.js
  src/views/DirectEditing.vue
  src/views/FilesSettings.vue
  src/views/RichWorkspace.vue
Labels: 3. to review, bug, design

#655 Check if the accessibility app is enabled
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  src/views/RichWorkspace.vue
Labels: 3. to review, backport-request, bug

#610 Avoid race condition when adding steps and fix step entries with duplicate versions
  appinfo/info.xml
  lib/Command/ResetDocument.php
  lib/Db/SessionMapper.php
  lib/Db/StepMapper.php
  lib/Service/DocumentService.php
Labels: 3. to review, backport-request, bug

#671 [stable18] Check if the accessibility app is enabled
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  src/views/RichWorkspace.vue
Labels: 3. to review, bug

#686 Use horiziontal scrolling instead of wrapping in code block
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/preview.js
  js/preview.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
Labels: 4. to release, backport-request, enhancement
