Repository nextcloud/text, pull requests merged in 2020-12, with the labels that each got.

#1202 Catch possible database exceptions when fetching document data
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  src/components/EditorWrapper.vue
  src/services/PollingBackend.js
Labels: 4. to release, backport-request, bug

#1223 Revert removal of transformResponse
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~editor~files-modal.js
  js/vendors~editor~files-modal.js.map
  js/vendors~files-modal.js
  js/vendors~files-modal.js.map
  js/viewer.js
  js/viewer.js.map
  src/services/SyncService.js
Labels: 3. to review, backport-request, bug, bug: regression

#1221 [stable20] Catch possible database exceptions when fetching document data
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  src/components/EditorWrapper.vue
  src/services/PollingBackend.js
Labels: 3. to review, bug

#1222 [stable19] Catch possible database exceptions when fetching document data
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  src/components/EditorWrapper.vue
  src/services/PollingBackend.js
Labels: 3. to review, bug

#1015 Use to correct cache to obtain version info
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
Labels: 3. to review, enhancement

#1292 [stable18] Handle 403 errors the same as not found
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  src/services/PollingBackend.js
Labels: 3. to review, bug

#1294 [stable19] fix: use OC.Files API to get file info
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendor.js
  js/vendor.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor-rich~files-modal.js
  js/vendors~editor-rich~files-modal.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~editor~files-modal.js
  js/vendors~editor~files-modal.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/MenuBar.vue
  src/helpers/files.js
Labels: 3. to review, bug

#1295 [stable19] Fix link menu positioning
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/MenuBubble.vue
Labels: 3. to review, bug

#1293 [stable18] fix: use OC.Files API to get file info
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendor.js
  js/vendor.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js
  js/vendors~editor-collab~editor-guest~editor-rich~files-modal.js.map
  js/vendors~editor-rich.js
  js/vendors~editor-rich.js.map
  js/vendors~editor-rich~files-modal.js
  js/vendors~editor-rich~files-modal.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/vendors~editor~files-modal.js
  js/vendors~editor~files-modal.js.map
  src/components/MenuBar.vue
  src/helpers/files.js
Labels: 3. to review, bug

#1308 Add PHP-CS
  .github/workflows/lint.yml
  .php_cs.dist
  appinfo/routes.php
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Command/ResetDocument.php
  lib/Controller/DirectSessionController.php
  lib/Controller/NavigationController.php
  lib/Controller/PublicSessionController.php
  lib/Controller/SessionController.php
  lib/Controller/SettingsController.php
  lib/Controller/WorkspaceController.php
  lib/Cron/Cleanup.php
  lib/DAV/WorkspacePlugin.php
  lib/Db/Document.php
  lib/Db/DocumentMapper.php
  lib/Db/Session.php
  lib/Db/SessionMapper.php
  lib/Db/Step.php
  lib/Db/StepMapper.php
  lib/DirectEditing/TextDirectEditor.php
  lib/DirectEditing/TextDocumentCreator.php
  lib/DocumentHasUnsavedChangesException.php
  lib/DocumentSaveConflictException.php
  lib/Migration/Version030201Date20201116110353.php
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  lib/Service/SessionService.php
  lib/Service/WorkspaceService.php
  lib/VersionMismatchException.php
  tests/TextTest.php
Labels: 4. to release
