Repository nextcloud/text, pull requests merged in 2021-11, with the labels that each got.

#1903 Position menububble relative to content-wrapper
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
  src/components/MenuBubble.vue
  src/views/RichWorkspace.vue
Labels: bug, 3. to review

#1948 Update npm and node engines versions
  package.json
Labels: dependencies

#1962 Add remove link button
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/MenuBubble.vue
Labels: enhancement, 3. to review, format: markdown

#1959 Hide menu and keep focus when using menubar popover items
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/MenuBar.vue
Labels: bug, 4. to release, backport-request
