Repository nextcloud/text, pull requests merged in 2021-03, with the labels that each got.

#1488 Use write permission when possible
  lib/Service/DocumentService.php
Labels: 3. to review, bug

#1419 Fix clicking links with color annotations
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/marks/index.js
Labels: 4. to release, backport-request, bug, bug: regression

#1487 Formatting design details
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
Labels: 4. to release, design, enhancement, feature: formatting
