Repository nextcloud/text, pull requests merged in 2021-10, with the labels that each got.

#1770 [stable21] fix: rich workspaces overlap with new file dropdown
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/EditorWrapper.vue
Labels: 3. to review

#1884 Additional checks for workspace controller
  lib/Controller/WorkspaceController.php
Labels: bug, 3. to review, backport-request

#1916 Only register trailing node for rich text editing
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/EditorFactory.js
Labels: bug, 3. to review, bug: regression
