Repository nextcloud/text, pull requests merged in 2021-01, with the labels that each got.

#1313 Fix dbal types
  lib/Migration/Version010000Date20190617184535.php
  lib/Migration/Version030201Date20201116123153.php
  psalm.xml
Labels: 4. to release, bug

#1385 Track authors by step rather than transaction
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/vendors~editor-collab~editor-guest.js
  js/vendors~editor-collab~editor-guest.js.map
  js/vendors~editor.js
  js/vendors~editor.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/EditorWrapper.vue
  src/components/SessionList.vue
  src/extensions/UserColor.js
  src/extensions/tracking/TrackState.js
  src/extensions/tracking/models.js
  src/mixins/store.js
  src/services/PollingBackend.js
  src/store.js
Labels: 3. to review, bug: regression

#1386 Only increase refetch timer if we have all initial steps loaded
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/services/PollingBackend.js
Labels: 3. to review, enhancement, performance
