Repository nextcloud/text, pull requests merged in 2021-07, with the labels that each got.

#1716 Unify error responses and add logging where appropriate
  lib/Controller/WorkspaceController.php
Labels: 3. to review, backport-request, bug

#1574 fix: rich workspaces overlap with new file dropdown
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
Labels: 3. to review, bug

#1769 [stable22] fix: rich workspaces overlap with new file dropdown
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/EditorWrapper.vue
Labels: 4. to release

#1776 Update use of `OCA.Viewer` api to the nextcloud 22 version
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/helpers/links.js
  src/tests/helpers/links.spec.js
Labels: 3. to review, bug, bug: regression

#1777 change tab-size to 4
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
Labels: 3. to review, design, enhancement

#1778 Extend mimetypes for direct editing
  lib/DirectEditing/TextDirectEditor.php
Labels: 3. to review, enhancement

#1795 Avoid creating invalid URIs from user input
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/MenuBubble.vue
Labels: 3. to review, bug

#1796 Make occ command return an integer as return code
  lib/Command/ResetDocument.php
Labels: 3. to review
