Repository nextcloud/text, pull requests merged in 2022-03, with the labels that each got.

#2168 [master] Render data URL images as-is
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/ImageView.vue
  src/tests/nodes/ImageView.spec.js
Labels: bug, 3. to review

#2153 [stable23] Render data URL images as-is
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/ImageView.vue
  src/tests/nodes/ImageView.spec.js
Labels: bug, 4. to release

#2193 use filelist PROPFIND for loading workspace
  .github/workflows/cypress.yml
  cypress/integration/share.spec.js
  cypress/integration/workspace.spec.js
  cypress/server.sh
  cypress/support/commands.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/DAV/WorkspacePlugin.php
  src/components/EditorWrapper.vue
  src/extensions/Collaboration.js
  src/helpers/files.js
  src/services/PollingBackend.js
  src/views/RichWorkspace.vue
Labels: enhancement, 3. to review, performance 🚀

#2107 test: closing the non-viewer modal in shared folder
  cypress/integration/share.spec.js
Labels: tests, 2. developing

#2188 Fix/2018 task list indication
  css/icons.scss
  cypress/fixtures/ListItem.md
  cypress/integration/ListItem.spec.js
  cypress/integration/workspace.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/utils/index.js
  img/tasklist.svg
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  js/vendors.js
  package-lock.json
  package.json
  src/EditorFactory.js
  src/markdownit/index.js
  src/markdownit/splitMixedLists.js
  src/mixins/menubar.js
  src/nodes/BulletList.js
  src/nodes/ListItem.js
  src/nodes/TaskItem.js
  src/nodes/TaskList.js
  src/nodes/index.js
  src/tests/extensions/Markdown.spec.js
  src/tests/markdown.spec.js
  src/tests/markdownit.spec.js
  src/tests/nodes/ListItem.spec.js
  src/tests/nodes/TaskItem.spec.js
Labels: bug, 3. to review, technical debt

#2216 fix: workspace with Readme.md open details.
  cypress/integration/workspace.spec.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/helpers/files.js
Labels: 4. to release, bug: regression

#2221 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#2222 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#2223 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#2226 display content first and then load menus
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
  src/components/MenuBar.vue
Labels: enhancement, 3. to review, performance 🚀

#2225 Performance/create session with content
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/Service/ApiService.php
  src/components/EditorWrapper.vue
  src/services/SyncService.js
Labels: enhancement, 3. to review, performance 🚀

#2236 Support PHP 8.1
  .github/workflows/lint.yml
  .github/workflows/phpunit.yml
  .github/workflows/static-analysis.yml
  lib/Db/Document.php
  lib/Db/Session.php
  lib/Db/Step.php
Labels: enhancement, 3. to review

#2069 Fix Content-type of served images
  lib/Controller/ImageController.php
Labels: bug, 1. to develop

#2253 Replace deprecated String.prototype.substr()
  cypress/utils/index.js
Labels: 3. to review

#2261 Fix a deprecation warning about returning bool from comparison function
  lib/Service/DocumentService.php
Labels: 3. to review

#2265 Allow pasting an image from the clipboard
  src/components/EditorWrapper.vue
  src/nodes/Image.js
Labels: enhancement, 3. to review, format: markdown
