Repository nextcloud/text, pull requests merged in 2022-11, with the labels that each got.

#3347 Fix inputRegex for TaskItem to not mark empty checkbox as checked
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/TaskItem.js
Labels: bug, 3. to review, format: markdown

#3288 TaskItem: Don't allow toggling while editor is readonly
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/TaskItem.js
Labels: bug, 4. to release

#3321 Remove trailing newline from code blocks
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/CodeBlock.js
Labels: bug, 3. to review

#3341 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3366 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3365 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3356 DirectEditing: Set session user for DirectSession editing
  lib/Controller/DirectSessionController.php
Labels: bug, 3. to review, backport-request

#3349 Disable rich workspace rendering when view is not visible
  cypress/e2e/workspace.spec.js
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/helpers/files.js
  src/views/RichWorkspace.vue
Labels: bug, 3. to review, backport-request

#3378 Pin @nextcloud/eslint-config and @nextcloud/webpack-vue-config for stable23/stable24
  renovate.json
Labels: dependencies, 3. to review

#3350 Don't apply author annotations when in composition
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/extensions/UserColor.js
Labels: bug, 3. to review, backport-request

#3390 Set IUserSession user in SessionController if available
  lib/Controller/SessionController.php
Labels: backport-request

#3394 update: use cypress action v4
  .github/workflows/cypress.yml
Labels: dependencies

#3401 Add tests for direct editing and cleanup dead code
  cypress/e2e/directediting.spec.js
  cypress/support/commands.js
  lib/Controller/DirectSessionController.php
Labels: tests, 3. to review, technical debt

#3403 [stable24] Disable rich workspace rendering when view is not visible
  js/editor-rich.js
  js/editor-rich.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/helpers/files.js
  src/views/RichWorkspace.vue
Labels: bug, 3. to review

#2716 Add paste event handler to allow pasting markdown
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/extensions/Markdown.js
Labels: enhancement, 4. to release

#3388 Fix hard line breaks displayed with additional new line between
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/markdownit/index.js
  src/tests/markdown.spec.js
  src/tests/nodes/Table.spec.js
  src/tests/tiptap.spec.js
Labels: bug, 3. to review, javascript

#3420 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3418 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3419 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3416 [stable25] Fix hard line breaks displayed with additional new line between
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/markdownit/index.js
  src/tests/markdown.spec.js
  src/tests/nodes/Table.spec.js
  src/tests/tiptap.spec.js
Labels: bug, 2. developing

#2757 Bring back menubar without formatting on plain text mode
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/components/Editor/SessionList.vue
  src/components/Menu/MenuBar.vue
  src/components/Menu/ReadonlyBar.vue
Labels: bug, 3. to review, backport-request

#3445 Fix block images always add additional newlines on the end of the file
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/Image.js
  src/nodes/ImageInline.js
  src/tests/extensions/Markdown.spec.js
  src/tests/markdown.spec.js
  src/tests/markdownit.spec.js
Labels: bug, feature: formatting, 3. to review, bug: regression

#3460 Fix front matter rendering
  cypress/README.md
  cypress/e2e/FrontMatter.spec.js
  cypress/support/commands.js
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/markdownit/index.js
  src/nodes/FrontMatter.js
  src/tests/markdown.spec.js
Labels: feature: formatting, 3. to review, format: markdown

#3450 Fix notification icon color
  img/app-dark.svg
  lib/Notification/Notifier.php
Labels: bug, 3. to review, backport-request, accessibility

#3464 Fix mention uid autocomplete and keyboard handler in list nodes
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/Controller/UserApiController.php
  src/extensions/RichText.js
Labels: bug, 3. to review, backport-request

#3472 Use GH ref as cypress run title
  .github/workflows/cypress.yml
Labels: tests, 4. to release

#3473 Use GH ref as cypress run title²
  .github/workflows/cypress.yml
Labels: 3. to review

#3476 Fix direct editing loading of txt files
  cypress/e2e/directediting.spec.js
  cypress/fixtures/empty.txt
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/DirectEditing/TextDirectEditor.php
  src/services/SyncService.js
Labels: bug, 2. developing, backport-request

#3480 [stable25] Combined code block backport
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/extensions/Markdown.js
  src/extensions/RichText.js
  src/nodes/CodeBlock.js
  src/tests/markdown.spec.js
Labels: bug, 3. to review

#3481 [Stable25] Backport of #3460 - Fix front matter rendering
  cypress/README.md
  cypress/e2e/FrontMatter.spec.js
  cypress/support/commands.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/markdownit/index.js
  src/nodes/FrontMatter.js
  src/tests/markdown.spec.js
Labels: 4. to release, bug: regression

#3479 [stable25] Fix direct editing loading of txt files
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/DirectEditing/TextDirectEditor.php
  src/services/SyncService.js
Labels: bug, 3. to review

#3492 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3443 ImageView: Show caption in full length when in readonly mode
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/ImageView.vue
Labels: design, 4. to release

#3502 Keep markdown syntax of hard line breaks
  js/editor.js
  js/editor.js.LICENSE.txt
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/extensions/RichText.js
  src/extensions/index.js
  src/markdownit/hardbreak.js
  src/markdownit/index.js
  src/nodes/HardBreak.js
  src/tests/markdown.spec.js
Labels: enhancement, 3. to review, format: markdown
