Repository nextcloud/text, pull requests merged in 2022-01, with the labels that each got.

#2039 fix: cypress login with new session feature
  cypress.json
  cypress/integration/files.spec.js
  cypress/integration/share.spec.js
  cypress/integration/viewer.spec.js
  cypress/support/commands.js
Labels: tests, 3. to review

#2060 Add Cypress tests for image insertion
  cypress/fixtures/github.png
  cypress/fixtures/table.png
  cypress/integration/images.spec.js
  cypress/support/commands.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  package-lock.json
  package.json
  src/components/MenuBar.vue
Labels: enhancement, tests, 3. to review

#2057 Backport/1883/stable22
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
Labels: bug, 3. to review

#2070 Trigger cypress on push/pull_request
  .github/workflows/cypress.yml
Labels: tests, 3. to review

#2059 Fix image serving in direct editing
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/Controller/ImageController.php
  src/nodes/ImageView.vue
Labels: bug, 3. to review

#2071 Factorize image upload cypress tests
  cypress/integration/images.spec.js
Labels: enhancement, tests, 3. to review

#2074 [stable22] Avoid creating invalid URIs from user input
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/MenuBubble.vue
Labels: bug, 4. to release

#2075 [stable22] allow to insert text after trailing codeblock
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/EditorFactory.js
Labels: bug, 3. to review

#2076 [stable22] Only register trailing node for rich text editing
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/EditorFactory.js
Labels: bug, 3. to review

#2027 update offline state message when saving
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
Labels: bug, 2. developing

#2052 fix: 2020 let heading menu overflow workspace
  cypress/integration/workspace.spec.js
  cypress/runLocal.sh
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
  src/components/MenuBubble.vue
  src/views/RichWorkspace.vue
Labels: bug, 3. to review

#2104 Fix closing the editor modal in public folder view
  js/editor-rich.js
  js/editor-rich.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/helpers/files.js
Labels: bug, 2. developing, backport-request

#2095 [stable22] Only show image author annotations if needed
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/components/EditorWrapper.vue
Labels: bug, 3. to review, backport-request

#2109 [stable23] fix: 2020 let heading menu overflow workspace
  cypress/integration/workspace.spec.js
  cypress/runLocal.sh
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  package-lock.json
  package.json
  src/components/EditorWrapper.vue
  src/components/MenuBubble.vue
  src/views/RichWorkspace.vue
Labels: backport-request

#2114 Create block-merge-freeze.yml
  .github/workflows/block-merge-freeze.yml
Labels: backport-request

#1960 fix issues on formatting bar
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
  src/components/MenuBar.vue
  src/components/SessionList.vue
Labels: bug, design, 3. to review

#2128 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies
