Repository nextcloud/text, pull requests merged in 2022-04, with the labels that each got.

#2268 Fix broken file links
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/marks/Link.js
Labels: 4. to release, bug: regression, feature: embed

#2244 Fix participant popover design
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/GuestNameDialog.vue
  src/components/SessionList.vue
Labels: 3. to review, design: papercut

#2289 Fix/2267 table tweaks
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/TableCellView.vue
  src/nodes/TableHeaderView.vue
  src/nodes/TableView.vue
Labels: bug, 3. to review

#2306 Fix matrix variable reference in Github static-analysis action
  .github/workflows/static-analysis.yml
  lib/Controller/ImageController.php
Labels: backport-request

#2307 Fix position of dropped images
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
  src/nodes/Image.js
Labels: bug, feature: formatting, 3. to review, backport-request, format: markdown

#2294 fix: keep menubar in one line - prioritize entries
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/MenuBar.vue
  src/mixins/menubar.js
Labels: backport-request

#2312 Fix modal heights
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
  src/components/HelpModal.vue
  src/components/ViewerComponent.vue
Labels: 3. to review, backport-request, bug: regression

#2316 Bugfix: add support to auto link
  cypress/fixtures/empty.md
  cypress/integration/links.spec.js
  cypress/support/commands.js
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/marks/Link.js
  src/plugins/link.js
Labels: enhancement, 3. to review, backport-request, bug: regression

#2319 [stable24] add support to auto link
  cypress/fixtures/empty.md
  cypress/integration/links.spec.js
  cypress/support/commands.js
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/marks/Link.js
  src/plugins/link.js
Labels: 3. to review, bug: regression

#2318 Small test adjusts
  cypress/integration/links.spec.js
  cypress/support/commands.js
Labels: enhancement, 3. to review

#2330 Adapt cypress login command to small change in login page
  cypress/support/commands.js
Labels: bug, tests, 3. to review

#2329 Fix drag&drop of non-image objects
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/Image.js
Labels: 3. to review, backport-request, bug: regression

#2336 Fix cypress tests on stable24
  .github/workflows/cypress.yml
  cypress/integration/workspace.spec.js
  cypress/support/commands.js
Labels: tests, 3. to review

#2340 Performance improviments
  cypress/integration/workspace.spec.js
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.provider.js
  src/components/EditorWrapper.vue
  src/components/GuestNameDialog.vue
  src/components/MenuBar.vue
  src/components/MenuBubble.vue
Labels: enhancement, 3. to review, 18-feedback, performance 🚀

#2315 fix: adjust menubar on sidebar toggling
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/MenuBar.vue
Labels: bug, 3. to review

#2292 Changes menu entry.
  js/editor-rich.js
  js/editor-rich.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/AppInfo/Application.php
  src/helpers/files.js
Labels: enhancement, 2. developing
