Repository nextcloud/text, pull requests merged in 2022-07, with the labels that each got.

#2668 Link handling fixes
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  package.json
  src/components/RichTextReader.vue
  src/helpers/links.js
  src/plugins/link.js
Labels: bug

#2658 fix: take retry into account for test folders
  cypress/e2e/workspace.spec.js
Labels: tests, 3. to review

#2608 Fix/dav
  cypress/e2e/propfind.spec.js
  cypress/support/commands.js
  lib/DAV/WorkspacePlugin.php
Labels: 3. to review, backport-request, bug: regression

#2659 [stable24] fix: return promise in cypress command to wait for it
  cypress/support/commands.js
Labels: tests, 3. to review

#2672 Backport link fixes to stable24
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/helpers/links.js
  src/marks/Link.js
  src/plugins/link.js
Labels: bug, 4. to release

#2678 Show display name instead of user id in frontend
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
Labels: enhancement, 3. to review

#2677 fix: use own workspace endpoint instead of PROPFIND properties
  js/editor-rich.js
  js/editor-rich.js.LICENSE.txt
  js/editor-rich.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.LICENSE.txt
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/helpers/files.js
  src/views/RichWorkspace.vue
Labels: bug, 4. to release, backport-request, performance 🚀

#2673 [stable24] fix: only show delete image button when editing
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/ImageView.vue
Labels: bug, 3. to review

#2627 Update toolbar button style
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Menu/ActionEntry.scss
Labels: enhancement, design, 3. to review

#2700 Do not unintended remove or modify link titles
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/marks/Link.js
  src/tests/markdown.spec.js
Labels: bug, 3. to review

#2706 Adapt to latest changes in OCP\Color
  lib/Service/SessionService.php
Labels: bug, 3. to review, bug: regression

#2711 Fix icon color on dark mode
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Menu/ActionEntry.scss
Labels: bug, 3. to review, bug: regression

#2714 Remove events from $editor before destroy it
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
Labels: 3. to review, technical debt, performance 🚀

#2719 Some backend cleanup
  composer.json
  composer.lock
  lib/Command/ResetDocument.php
  lib/Controller/DirectSessionController.php
  lib/Controller/ImageController.php
  lib/Controller/PublicSessionController.php
  lib/Controller/SessionController.php
  lib/Controller/SettingsController.php
  lib/Controller/WorkspaceController.php
  lib/Cron/Cleanup.php
  lib/Db/Document.php
  lib/Db/Session.php
  lib/Db/Step.php
  lib/Db/StepMapper.php
  lib/Exception/DocumentHasUnsavedChangesException.php
  lib/Exception/DocumentSaveConflictException.php
  lib/Exception/UploadException.php
  lib/Exception/VersionMismatchException.php
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  lib/Service/WorkspaceService.php
  lib/TextFile.php
  tests/psalm-baseline.xml
Labels: 4. to release, technical debt

#2717 RichWorkspace: improve keyboard controls
  cypress/e2e/workspace.spec.js
  js/editor-rich.js
  js/editor-rich.js.LICENSE.txt
  js/editor-rich.js.map
  js/text-files.js
  js/text-files.js.LICENSE.txt
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.LICENSE.txt
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/views/RichWorkspace.vue
Labels: enhancement, 4. to release, accessibility

#2715 Add missing aria labels
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
  src/components/Menu/ActionImageUpload.vue
  src/components/Menu/ActionList.vue
  src/components/Menu/ActionSingle.vue
  src/components/Menu/EmojiPickerAction.vue
  src/components/Menu/MenuBar.vue
Labels: 3. to review, accessibility

#2726 Remove focus border for text content
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
Labels: bug, 3. to review

#2730 Fix typo in `serializePlainText`
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/EditorFactory.js
  src/helpers/mappings.js
Labels: bug, 3. to review, backport-request, bug: regression

#2712 Disable formatting menububble in Safari on iOS
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
Labels: bug, 3. to review

#2728 [stable24] Make cypress CI faster
  .github/workflows/cypress.yml
Labels: tests, 3. to review

#2441 Improve Header bar
  css/style.scss
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
Labels: 3. to review

#2752 Fix bullet list input role for CJK input
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/BulletList.js
Labels: bug, feature: formatting, 3. to review

#2750 l10n: Separate words
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Menu/MenuBar.vue
Labels: 3. to review

#2660 cleanup: wait statements - rely on promises instead
  cypress/e2e/images.spec.js
  cypress/support/commands.js
Labels: tests, 3. to review, backport-request

#2754 Only autolink URLs containing protocol
  cypress/e2e/links.spec.js
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/extensions/RichText.js
Labels: bug, 4. to release

#2758 Only apply bold to the viewer title bar
  css/style.scss
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
Labels: bug, 3. to review

#2759 Nextcloud 25 - Share changes
  cypress/e2e/files.spec.js
  cypress/e2e/share.spec.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/helpers/files.js
  src/public.js
Labels: bug, 3. to review

#2687 Refactor: Split Editor Wrapper into multiple components
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.provider.js
  src/components/Editor.vue
  src/components/Editor/AvatarWrapper.vue
  src/components/Editor/Content.vue
  src/components/Editor/DocumentStatus.vue
  src/components/Editor/GuestNameDialog.vue
  src/components/Editor/Main.vue
  src/components/Editor/MediaHandler.provider.js
  src/components/Editor/MediaHandler.vue
  src/components/Editor/SessionList.vue
  src/components/Editor/Status.vue
  src/components/Editor/Wrapper.vue
  src/components/Menu/ActionImageUpload.vue
  src/components/Menu/BaseActionEntry.js
  src/components/Menu/MenuBar.vue
  src/components/MenuBubble.vue
  src/components/PublicFilesEditor.vue
  src/components/ViewerComponent.vue
  src/nodes/ImageView.vue
  src/package.js
  src/public.js
  src/views/DirectEditing.vue
  src/views/RichWorkspace.vue
Labels: 3. to review, technical debt

#2763 [a11y] add missing label/title
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/SessionList.vue
Labels: 3. to review, accessibility
