Repository nextcloud/text, pull requests merged in 2022-02, with the labels that each got.

#2139 Updating fixup.yml workflow from template
  .github/workflows/fixup.yml
Labels: dependencies

#2144 Use php 7.4 and 8.0 in drone CI
  .drone.yml
Labels: 3. to review, technical debt

#2143 Add index for last_contact in text_sessions table
  appinfo/info.xml
  lib/Migration/Version010000Date20190617184535.php
  lib/Migration/Version030501Date20220202101853.php
Labels: enhancement, 3. to review, performance

#2145 Use file.path to track EditorWrapper instances more accurately
  js/editor-rich.js
  js/editor-rich.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/views/RichWorkspace.vue
Labels: bug, 3. to review

#2167 Fix Cypress image tests
  cypress/integration/images.spec.js
Labels: bug, tests, 3. to review

#2149 [stable21] Add index for last_contact in text_sessions table
  appinfo/info.xml
  lib/Migration/Version010000Date20190617184535.php
  lib/Migration/Version030201Date20220202141726.php
Labels: 3. to review

#2148 [stable22] Add index for last_contact in text_sessions table
  appinfo/info.xml
  lib/Migration/Version010000Date20190617184535.php
  lib/Migration/Version030301Date20220202141528.php
Labels: 3. to review

#2147 [stable23] Add index for last_contact in text_sessions table
  appinfo/info.xml
  lib/Migration/Version010000Date20190617184535.php
  lib/Migration/Version030401Date20220203141002.php
Labels: 3. to review

#2151 [stable22] Use file.path to track more accurately EditorWrapper instances
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/views/RichWorkspace.vue
Labels: bug, 3. to review

#2152 [stable21] Use file.path to track more accurately EditorWrapper instances
  js/editor-rich.js
  js/editor-rich.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
  src/views/RichWorkspace.vue
Labels: bug, 3. to review

#2197 [stable22] fix: only apply bullet style to ul > li
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
Labels: bug, 3. to review

#2196 [stable21] fix: only apply bullet style to ul > li
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/files.js
  js/files.js.map
  js/public.js
  js/public.js.map
  js/text.js
  js/text.js.map
  js/viewer.js
  js/viewer.js.map
Labels: bug, 3. to review
