Repository nextcloud/text, pull requests merged in 2022-12, with the labels that each got.

#3512 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3503 Prevent file deletion when pressing Ctrl+Delete
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/extensions/Keymap.js
Labels: bug, 3. to review

#3504 Preserve HTML newlines and add support for newlines within table cells
  cypress/e2e/Table.spec.js
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/markdownit/hardbreak.js
  src/nodes/HardBreak.js
  src/nodes/Table/Table.js
  src/nodes/Table/TableCell.js
  src/tests/fixtures/table.html
  src/tests/fixtures/table.md
  src/tests/fixtures/tableWithOtherStructure.html
  src/tests/fixtures/tables/basic.out.html
  src/tests/markdown.spec.js
Labels: enhancement, 3. to review, format: markdown, ux

#3520 Prevent dangling debounced extractHeadings function
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  package.json
  src/nodes/Heading/index.js
Labels: tests, 3. to review

#3532 Only scroll images into view when they're added
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/MediaHandler.vue
  src/nodes/ImageView.vue
Labels: bug, 3. to review, backport-request

#3524 Emit event on file change
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
Labels: enhancement, 3. to review

#3528 Don't empty list of headings in onDestroy
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/TableOfContents.vue
  src/nodes/Heading/index.js
Labels: bug, 3. to review, backport-request

#3557 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3544 Fix design of `InlineActionsContainer` - resolv design review comments
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/InlineActionsContainer.vue
Labels: design, 3. to review

#3569 Use cypress helpers from `@nextcloud/cypress`
  cypress/README.md
  cypress/e2e/attachments.spec.js
  cypress/e2e/workspace.spec.js
  cypress/support/commands.js
Labels: enhancement, tests, 3. to review

#3568 Feat: backspace converts paragraph break to hard line break
  cypress/e2e/nodes/FrontMatter.spec.js
  cypress/e2e/nodes/HardBreak.spec.js
  cypress/e2e/nodes/ImageView.spec.js
  cypress/e2e/nodes/Links.spec.js
  cypress/e2e/nodes/ListItem.spec.js
  cypress/e2e/nodes/Mentions.spec.js
  cypress/e2e/nodes/Table.spec.js
  js/editor.js
  js/editor.js.LICENSE.txt
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/HelpModal.vue
  src/helpers/platform.js
  src/nodes/HardBreak.js
  src/nodes/Paragraph.js
Labels: enhancement, 3. to review, mobile

#3581 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3582 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3593 [stable25] Backport missing pieces for outline suport in Collectives
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/highlight/shell.js
  js/highlight/shell.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/BaseReader.vue
  src/components/Editor.vue
Labels: 3. to review

#3596 Increase idle timeout to one day (1440 minutes)
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/services/SyncService.js
Labels: 3. to review, backport-request

#3607 [stable23] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3606 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3616 Fix `this.editor` being undefined in markdown extension
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/extensions/Markdown.js
Labels: bug, 3. to review, javascript

#3617 Fix URL of GitHub workflow status badge
  README.md
Labels: bug, 3. to review

#3623 Treat newlines as linebreaks when pasting as plaintext
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/extensions/Markdown.js
Labels: 3. to review

#3625 [stable25] Treat newlines as linebreaks when pasting as plaintext
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/extensions/Markdown.js
Labels: 3. to review
