Repository nextcloud/text, pull requests merged in 2022-09, with the labels that each got.

#2841 Feature: Add page anchors (inter page links)
  css/prosemirror.scss
  cypress/e2e/outline.spec.js
  cypress/e2e/sections.spec.js
  cypress/support/chai.js
  cypress/support/commands.js
  cypress/support/e2e.js
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/helpers/links.js
  src/nodes/Heading/HeadingView.vue
  src/nodes/Heading/index.js
  src/plugins/link.js
Labels: enhancement, design, 3. to review, javascript

#2851 fix: readonly shares should not seem editable
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
Labels: bug, 3. to review, regression

#2852 Fix missing sharing token
  cypress/e2e/share.spec.js
  cypress/support/commands.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/ViewerComponent.vue
  src/helpers/files.js
  src/helpers/token.js
Labels: tests, 3. to review, bug: regression

#2862 Fix headlines being hidden behind toolbar (anchor links)
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/helpers/links.js
Labels: bug, 3. to review

#2860 Append a newline after inserted image
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/MediaHandler.vue
Labels: 3. to review, backport-request

#2378 Non-image media attachments
  appinfo/routes.php
  cypress/e2e/attachments.spec.js
  cypress/fixtures/file.txt.gz
  index.html
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/AppInfo/Application.php
  lib/Controller/AttachmentController.php
  lib/Cron/Cleanup.php
  lib/Listeners/BeforeNodeDeletedListener.php
  lib/Listeners/BeforeNodeRenamedListener.php
  lib/Listeners/NodeCopiedListener.php
  lib/Service/ApiService.php
  lib/Service/AttachmentService.php
  src/components/Editor.provider.js
  src/components/Editor.vue
  src/components/Editor/MediaHandler.provider.js
  src/components/Editor/MediaHandler.vue
  src/components/Menu/ActionAttachmentUpload.vue
  src/components/Menu/entries.js
  src/nodes/Image.js
  src/nodes/ImageView.vue
  src/package.js
  src/services/AttachmentResolver.js
  src/services/SyncService.js
  src/tests/services/AttachmentResolver.spec.js
  src/tests/services/ImageResolver.spec.js
  tests/psalm-baseline.xml
  tests/unit/Service/AttachmentServiceTest.php
Labels: enhancement, 2. developing, format: markdown

#2872 fix: update link menububble on editor updates
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/MenuBubble.vue
Labels: backport-request

#2877 ⏪️ Revert #2841 (page anchors)
  cypress/e2e/outline.spec.js
  cypress/e2e/sections.spec.js
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/Heading/HeadingView.vue
  src/nodes/Heading/index.js
Labels: 3. to review, bug: regression

#2867 Add printing style sheet, enables printing of text files
  css/print.scss
  css/prosemirror.scss
  css/style.scss
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  package.json
  src/components/Editor.vue
  src/components/RichTextReader.vue
Labels: enhancement, design, 3. to review

#2863 Fix emoji autocompletion keyboard behaviour
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/EditorFactory.js
  src/components/EmojiList.vue
  src/components/EmojiListWrapper.vue
Labels: 3. to review, backport-request, accessibility

#2914 Feat/page anchors
  cypress/e2e/outline.spec.js
  cypress/e2e/sections.spec.js
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/Heading/HeadingView.vue
  src/nodes/Heading/index.js
Labels: 3. to review

#2922 Remove focus-visible outline from headings
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/Heading/HeadingView.vue
Labels: design, 3. to review

#2972 Support heic/heif attachments as photos
  lib/Controller/AttachmentController.php
Labels: enhancement, 3. to review, feature: images

#2906 fix: solve escape key closing the editor issue
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
Labels: bug, 3. to review

#2975 [stable24] Make it possible to insert heif/heic images
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/Controller/ImageController.php
  src/components/EditorWrapper.vue
  src/components/MenuBar.vue
Labels: enhancement, 3. to review, feature: images

#3056 [stable24] Disable formatting menububble in Safari on iOS
  css/prosemirror.scss
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
Labels: bug, 3. to review

#2974 Add "preferRawImage" parameter to image attachment endpoint
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/Controller/AttachmentController.php
  lib/Service/AttachmentService.php
  src/services/AttachmentResolver.js
  src/tests/services/AttachmentResolver.spec.js
Labels: enhancement, 3. to review, feature: images

#3066 Fix: menubar throws errors on master focus trap too much recursion
  cypress/e2e/workspace.spec.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Menu/ActionAttachmentUpload.vue
  src/components/Menu/ActionList.vue
  src/components/Menu/EmojiPickerAction.vue
  src/components/Menu/MenuBar.provider.js
  src/components/Menu/MenuBar.vue
Labels: bug, tests, 3. to review, regression
