Repository nextcloud/text, pull requests merged in 2022-06, with the labels that each got.

#2481 Fix cypress scripts for local run + Add documentation
  README.md
  cypress.config.js
  cypress.json
  cypress/Dockerfile
  cypress/docker-compose.yml
  cypress/e2e/ListItem.spec.js
  cypress/e2e/Table.spec.js
  cypress/e2e/files.spec.js
  cypress/e2e/images.spec.js
  cypress/e2e/links.spec.js
  cypress/e2e/share.spec.js
  cypress/e2e/viewer.spec.js
  cypress/e2e/workspace.spec.js
  cypress/runLocal.sh
  cypress/server.sh
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: enhancement, tests, dependencies, 3. to review

#2493 [stable23] Fix composer dependencies
  composer.json
  composer.lock
  tests/psalm-baseline.xml
Labels: dependencies, 3. to review

#2494 Make cypress CI faster
  .github/workflows/cypress.yml
Labels: tests, 3. to review

#2446 Encode file to UTF-8 on `fetch` call
  lib/Service/ApiService.php
  lib/TextFile.php
Labels: enhancement, 3. to review

#2495 An empty string is a valid encoded result
  cypress/e2e/viewer.spec.js
  lib/Service/ApiService.php
  lib/Service/EncodingService.php
  lib/TextFile.php
Labels: bug, 3. to review

#2447 Avoid random guest names and make guest state more visible
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/Service/ApiService.php
  lib/Service/SessionService.php
  src/components/AvatarWrapper.vue
  src/components/EditorWrapper.vue
  src/components/GuestNameDialog.vue
  src/components/SessionList.vue
  src/helpers/index.js
  tests/psalm-baseline.xml
Labels: enhancement, 3. to review

#2467 Use better wording in english to allow easier gender neutral translations
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/GuestNameDialog.vue
  src/components/SessionList.vue
Labels: bug, 4. to release

#2604 Susnux fix/formatting help
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Menu/ActionList.vue
Labels: bug, 3. to review

#2506 l10n: Correct spelling
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/ImageView.vue
Labels: bug, 4. to release

#2513 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#2496 Avoid loading the image before the node view
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/Image.js
Labels: bug, 3. to review

#2512 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#2515 Fix docker container for local cypress tests
  cypress/Dockerfile
  cypress/docker-compose.yml
  cypress/entrypoint.sh
  cypress/runLocal.sh
  cypress/server.sh
Labels: enhancement, tests, 3. to review
