Repository nextcloud/text, pull requests merged in 2022-08, with the labels that each got.

#2762 [a11y] add aria-keyshortcuts
  cypress/e2e/shortcuts.spec.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Menu/ActionSingle.vue
  src/components/Menu/BaseActionEntry.js
  src/components/Menu/entries.js
  src/components/Menu/keys.js
  src/components/Menu/utils.js
Labels: enhancement, tests, 3. to review, accessibility

#2773 Fix alignment of questionmark in guest avatar
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor-guest.js
  js/editor-guest.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/AvatarWrapper.vue
Labels: 3. to review, bug: regression, design: papercut

#2782 Update npm and node engines versions
  package.json
Labels: dependencies

#2804 Avoid duplicate queries that were caused by running execute and the mapper find method
  lib/Db/SessionMapper.php
  lib/Db/StepMapper.php
Labels: bug, 3. to review, performance 🚀

#2688 Outline view
  css/prosemirror.scss
  css/style.scss
  cypress/e2e/outline.spec.js
  cypress/support/commands.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.LICENSE.txt
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.LICENSE.txt
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.LICENSE.txt
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  js/vendors.js
  package-lock.json
  package.json
  src/EditorFactory.js
  src/components/Editor.vue
  src/components/Editor/Content.vue
  src/components/Editor/EditorOutline.vue
  src/components/Editor/TableOfContents.vue
  src/components/Editor/Wrapper.provider.js
  src/components/Editor/Wrapper.vue
  src/components/Menu/ActionList.vue
  src/components/Menu/ActionSingle.vue
  src/components/Menu/BaseActionEntry.js
  src/components/Menu/entries.js
  src/components/Menu/utils.js
  src/components/icons.js
  src/extensions/RichText.js
  src/files.js
  src/helpers/files.js
  src/main.js
  src/mixins/isMobile.js
  src/mixins/store.js
  src/nodes/Heading.js
  src/nodes/Heading/extractor.js
  src/nodes/Heading/index.js
  src/nodes/Heading/slug.js
  src/public.js
  src/store.js
  src/store/index.js
  src/store/mutation-types.js
  src/store/plugin.js
Labels: enhancement, design, 3. to review

#2795 Disable background fade on empty rih workspace
  js/editor-rich.js
  js/editor-rich.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/views/RichWorkspace.vue
Labels: bug, 3. to review, accessibility

#2805 Use displayname cache for fetching session data
  lib/Service/SessionService.php
Labels: 3. to review, performance 🚀

#2826 Refactor regex for keeping syntax to support Safari
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/markdownit/keepSyntax.js
Labels: bug, 3. to review

#2831 Fix reset occ command
  lib/Db/StepMapper.php
  lib/Service/DocumentService.php
Labels: bug, 3. to review

#2686 Avoid saving without changes
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/EditorFactory.js
  src/tests/fixtures/tables/basic.out.html
  src/tests/fixtures/tables/handbook.out.html
  src/tests/markdown.spec.js
Labels: bug, 2. developing, backport-request
