Repository nextcloud/text, pull requests merged in 2022-05, with the labels that each got.

#2362 cleanup: explicit dependency on jest-environment-jsdom
  package-lock.json
  package.json
Labels: 3. to review

#2360 [stable22] fix: use node workflow from template
  .github/workflows/node.yml
  .github/workflows/nodejs.yml
Labels: tests, 3. to review, technical debt

#2361 ci: bump dependabot target branches
  .github/dependabot.yml
Labels: 3. to review, release

#2367 Switch to auto table layout
  css/prosemirror.scss
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/TableHeaderView.vue
Labels: 3. to review, backport-request, design: papercut

#2376 Use '(n)' suffix instead of timestamp prefix for uploaded image names
  lib/Service/ImageService.php
  tests/TextTest.php
Labels: enhancement, 3. to review, feature: embed, format: markdown

#2370 Manually get a mounted instance of the file if needed during lock/unlock
  lib/Service/DocumentService.php
Labels: bug, 3. to review, backport-request, bug: regression

#2373 🐛 fix viewer integration styling
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
  src/components/ViewerComponent.vue
Labels: bug, 3. to review, bug: regression

#2359 fix: only show delete image button when editing
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/ImageView.vue
  src/tests/nodes/ImageView.spec.js
Labels: 3. to review

#2383 Fix attachment cleanup when file names contain parenthesis
  cypress/integration/images.spec.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
  src/nodes/ImageView.vue
  tests/TextTest.php
Labels: 3. to review, bug: regression, format: markdown

#2390 Ignore files produced by phpunit
  .gitignore
Labels: 3. to review

#2389 [stable24] Fix attachment cleanup when file names contain parenthesis
  cypress/integration/images.spec.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/EditorWrapper.vue
  src/nodes/ImageView.vue
  tests/TextTest.php
Labels: 3. to review, bug: regression, format: markdown

#2393 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#2426 Improve image attachment management
  cypress/integration/images.spec.js
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/Service/ImageService.php
  src/components/EditorWrapper.vue
  src/nodes/ImageView.vue
  src/tests/nodes/ImageView.spec.js
  tests/unit/Service/ImageServiceTest.php
Labels: enhancement, feature: formatting, 3. to review, format: markdown

#2448 Do not register text/csv mimetype when office can handle it
  js/editor-rich.js
  js/editor-rich.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/helpers/mime.js
Labels: bug, 3. to review
