Repository nextcloud/text, pull requests merged in 2023-12, with the labels that each got.

#5077 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5078 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5084 Handle null file in RichWorkspace header
  src/views/RichWorkspace.vue
Labels: bug, 3. to review, backport-request, javascript

#5085 [stable27] Introduce middleware for session handling
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  cypress/e2e/api/SessionApi.spec.js
  cypress/e2e/api/UsersApi.spec.js
  cypress/support/sessions.js
  lib/AppInfo/Application.php
  lib/Controller/ASessionAwareController.php
  lib/Controller/AttachmentController.php
  lib/Controller/SessionController.php
  lib/Controller/UserApiController.php
  lib/Exception/InvalidSessionException.php
  lib/Middleware/Attribute/RequireDocumentSession.php
  lib/Middleware/SessionMiddleware.php
  lib/Service/AttachmentService.php
  lib/Service/SessionService.php
  src/services/SessionApi.js
  tests/unit/Controller/UserApiControllerTest.php
Labels: 3. to review, technical debt

#5090 chore(deps): Move `cypress-visual-regression` to dev dependencies
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#5095 feat(editor): Enable gapcursor, allows to put cursor between images
  package-lock.json
  package.json
  src/components/Editor/MediaHandler.vue
  src/extensions/RichText.js
Labels: 3. to review, ux

#5081 fix: cypress error
  package-lock.json
  package.json
  src/components/Editor/EditorOutline.vue
  src/nodes/Heading/index.js
Labels: 3. to review

#5124 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5129 Cypress: Improve request token handling, attachments test
  .github/workflows/cypress.yml
  cypress/e2e/attachments.spec.js
  cypress/support/commands.js
  package-lock.json
  package.json
Labels: backport-request

#5141 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5126 Preserve step queue during reconnect
  cypress/e2e/api/SyncServiceProvider.spec.js
  src/components/Editor.vue
  src/services/SyncServiceProvider.js
  src/services/WebSocketPolyfill.js
  src/tests/services/WebsocketPolyfill.spec.js
Labels: bug, 2. developing

#5148 fix(gapcursor): Don't allow gap cursor in tables
  src/nodes/Table/TableCaption.js
  src/nodes/Table/TableHeadRow.js
  src/nodes/Table/TableRow.js
Labels: 3. to review, backport-request, bug: regression

#5159 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5160 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5155 chore: Update krankerl config
  .nextcloudignore
  krankerl.toml
Labels: backport-request

#5167 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
Labels: dependencies, 3. to review, automated

#5098 fix(a11y): contrast for active menubar buttons
  cypress/e2e/workspace.spec.js
  src/components/Menu/ActionEntry.scss
  src/components/Menu/ActionList.vue
  src/components/Menu/ActionSingle.vue
  src/components/Menu/MenuBar.vue
Labels: bug, 2. developing, backport-request, accessibility

#5166 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
Labels: dependencies, 3. to review, automated

#5106 feat: check and apply markdown for smart picker output
  src/components/Suggestion/LinkPicker/suggestions.js
Labels: enhancement, 3. to review
