Repository nextcloud/text, pull requests merged in 2023-03, with the labels that each got.

#3856 Widget fixes
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/Listeners/LoadEditorListener.php
  src/nodes/ParagraphView.vue
Labels: bug, 3. to review

#3882 Fix provider name overflow in LinkPickerList
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Suggestion/LinkPicker/LinkPickerList.vue
Labels: bug, 3. to review, backport-request, feature: integration

#3873 Use the href of links for link previews, not `node.textContent`
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/ParagraphView.vue
Labels: bug, 4. to release, backport-request

#3884 fix: Hide author color UI until issues are resolved
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/SessionList.vue
Labels: bug, 3. to review, backport-request

#3890 fix: load fresh session if none are remaining
  cypress/e2e/SessionApi.spec.js
  cypress/support/sessions.js
  lib/Service/ApiService.php
Labels: backport-request

#3893 fix: only initialize editor once
  cypress/e2e/sync.spec.js
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
Labels: bug, 3. to review, backport-request, 26 feedback

#3901 fix: 403 when session is closed during push
  cypress/support/sessions.js
  lib/Service/ApiService.php
Labels: backport-request

#3891 [stable26] fix: load fresh session if none are remaining
  cypress/e2e/SessionApi.spec.js
  cypress/support/sessions.js
  lib/Service/ApiService.php
Labels: bug, 4. to release, feature: sync, backported, 26 feedback

#3900 [stable26] fix: only initialize editor once
  cypress/e2e/sync.spec.js
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
Labels: bug, 3. to review, backported, 26 feedback

#3905 [stable25] Only open direct link files if link points to Files app
  cypress/e2e/links.spec.js
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/helpers/links.js
Labels: bug, 3. to review

#3908 Avoid cleanup on close to not run into race conditions with other sessions on the same document
  cypress/e2e/SessionApi.spec.js
  cypress/e2e/sync.spec.js
  lib/Controller/PublicSessionController.php
  lib/Controller/SessionController.php
  lib/Cron/Cleanup.php
  lib/Db/DocumentMapper.php
  lib/Db/SessionMapper.php
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  lib/Service/SessionService.php
Labels: bug, backport-request, bug: regression, high, php, 26 feedback

#3910 Allow to scroll tables horizontally
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/Table/TableView.vue
Labels: bug, 4. to release, backport-request, accessibility

#3932 [stable26] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: dependencies, 3. to review

#3938 [stable25] Allow to scroll tables horizontally
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/Table/TableView.vue
Labels: 4. to release

#3941 feat: Add Shift-Mod-C for copying the markdown source
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
Labels: enhancement, 3. to review

#3951 fix: split layout of conflict view
  cypress/e2e/sync.spec.js
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
Labels: backport-request

#3942 [stable26] feat: Add Shift-Mod-C for copying the markdown source
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
Labels: 4. to release

#3969 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3975 Emit events from editor when image nodes get added or deleted
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/components/Editor/MediaHandler.vue
  src/nodes/ImageView.vue
Labels: 3. to review, backport-request

#3985 Prepare for 27.0.0-alpha.1 NPM release
  package.json
Labels: 4. to release

#3972 Conflict fixes
  cypress/e2e/conflict.spec.js
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/Service/DocumentService.php
  src/components/CollisionResolveDialog.vue
  src/components/Editor.vue
  src/components/Editor/DocumentStatus.vue
  src/services/PollingBackend.js
Labels: bug, 4. to release, backport-request, 26 feedback

#3996 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3997 Make saving indicator a button for force-save
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/Status.vue
  src/components/SavingIndicator.vue
Labels: bug, 3. to review, backport-request

#4007 Use `max-height` in DocumentStatus, fixes empty 50px bar above toolbar
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/DocumentStatus.vue
Labels: 3. to review, backport-request, bug: regression
