Repository nextcloud/text, pull requests merged in 2023-06, with the labels that each got.

#4236 fix: fix and upgrade cypress workflow
  .github/workflows/cypress.yml
Labels: 2. developing

#4229 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4243 ci(block-merge-freeze): Fix picking master branch for server
  .github/workflows/block-merge-freeze.yml
Labels: 3. to review

#4241 fix(UserApiController): Fix warning during test run with PHP 8.2
  lib/Controller/UserApiController.php
  tests/unit/Controller/UserApiControllerTest.php
Labels: bug, 3. to review

#4255 Limit cypress to github runners
  .github/workflows/cypress.yml
Labels: backport-request

#4248 No more deprecated API usages
  lib/Db/DocumentMapper.php
  lib/Db/SessionMapper.php
  lib/Db/StepMapper.php
  lib/DirectEditing/TextDirectEditor.php
  lib/Service/NotificationService.php
  lib/Service/SessionService.php
  psalm.xml
Labels: 3. to review, technical debt

#4240 [stable26] ci: Backport relevant action changes from main
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/cypress.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: tests, 3. to review

#3906 fix: paste multiple line to table issue
  cypress/e2e/nodes/Table.spec.js
  cypress/e2e/workspace.spec.js
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/Table/TableCell.js
Labels: bug, 3. to review

#4266 Introduce middleware for session handling
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  cypress/e2e/api/SessionApi.spec.js
  cypress/e2e/api/UsersApi.spec.js
  cypress/support/sessions.js
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/AppInfo/Application.php
  lib/Controller/ASessionAwareController.php
  lib/Controller/AttachmentController.php
  lib/Controller/SessionController.php
  lib/Controller/UserApiController.php
  lib/Db/SessionMapper.php
  lib/Exception/InvalidSessionException.php
  lib/Middleware/Attribute/RequireDocumentSession.php
  lib/Middleware/SessionMiddleware.php
  lib/Service/AttachmentService.php
  lib/Service/SessionService.php
  src/services/SessionApi.js
  tests/unit/Controller/UserApiControllerTest.php
Labels: 4. to release, technical debt

#4289 fix: Catch unique constraint violation when creating new documents
  lib/Service/DocumentService.php
Labels: bug, 3. to review

#4291 chore: Bump composer autoloader for new composer version
  composer/composer/ClassLoader.php
Labels: 3. to review

#4300 fix(cypress): shortcut test retry
  cypress/e2e/shortcuts.spec.js
Labels: tests, 3. to review, technical debt, Nice to have

#4301 fix(css): info callout box color to --color-info
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/Callout.vue
Labels: bug, 3. to review, backport-request, ux

#4285 Fix/2708 pasting tables
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/PlainTextReader.vue
  src/extensions/PlainText.js
  src/nodes/Table/TableHeadRow.js
  src/nodes/Table/TableRow.js
  src/tests/helpers.js
  src/tests/markdown.spec.js
Labels: bug, 3. to review, backport-request, format: markdown

#4286 fix(sync): Save even if versions match
  cypress/e2e/directediting.spec.js
  lib/Service/DocumentService.php
Labels: bug, 4. to release, feature: sync

#4251 Bring back keyboard shortcuts to help modal on non-mobile
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/HelpModal.vue
Labels: 4. to release, backport-request, bug: regression

#4309 fix: Pass origin along the initial state update
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/helpers/yjs.js
Labels: bug, 4. to release, backport-request

#4312 fix: clickable zone of task list checkbox
  css/prosemirror.scss
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
Labels: bug, 4. to release

#4318 chore(css): Move CSS files to src directory
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/components/HelpModal.vue
  src/components/RichTextReader.vue
  src/css/print.scss
  src/css/prosemirror.scss
  src/css/style.scss
Labels: 4. to release, technical debt

#4327 fix: link preview width on mobile
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/ParagraphView.vue
Labels: bug, 4. to release, backport-request

#4328 chore(dependencies): Skip tiptap/prosemirror updates for 25
  renovate.json
Labels: dependencies, 3. to review

#4335 chore: update node engines to next LTS
  package.json
Labels: dependencies, 3. to review, automated

#4297 Emit sync event after successful push to pick up syncing again
  cypress/e2e/sync.spec.js
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/services/SyncService.js
Labels: bug, 4. to release

#4337 fix: max width of editor container on mobile
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/ContentContainer.vue
Labels: bug, 4. to release, mobile

#4307 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 4. to release

#4326 [stable25] fix: paste tables into document
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/Table/TableHeadRow.js
  src/nodes/Table/TableRow.js
  src/tests/markdown.spec.js
Labels: 3. to review

#4345 fix: Replace invalid sass rules with correct ones
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/css/prosemirror.scss
  src/nodes/Callout.vue
Labels: bug, 4. to release

#4357 ci/flaky runners
  .github/workflows/cypress.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
Labels: tests, 3. to review

#4290 Make use of session middleware in remaining controllers
  appinfo/routes.php
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  cypress/e2e/api/UsersApi.spec.js
  lib/Controller/ASessionAwareController.php
  lib/Controller/AttachmentController.php
  lib/Controller/ISessionAwareController.php
  lib/Controller/PublicSessionController.php
  lib/Controller/SessionController.php
  lib/Controller/SettingsController.php
  lib/Controller/TSessionAwareController.php
  lib/Controller/UserApiController.php
  lib/Controller/WorkspaceController.php
  lib/DirectEditing/TextDirectEditor.php
  lib/DirectEditing/TextDocumentCreator.php
  lib/Listeners/BeforeNodeDeletedListener.php
  lib/Listeners/BeforeNodeRenamedListener.php
  lib/Listeners/NodeCopiedListener.php
  lib/Middleware/SessionMiddleware.php
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  lib/Service/SessionService.php
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: 3. to review, technical debt, performance 🚀

#4364 Rework cypress commands
  cypress/e2e/attachments.spec.js
  cypress/e2e/nodes/ImageView.spec.js
  cypress/e2e/nodes/Mentions.spec.js
  cypress/e2e/sync.spec.js
  cypress/support/commands.js
  package-lock.json
  package.json
Labels: tests, 3. to review

#4393 ci(workflows): Update Github workflows from templates
  .github/workflows/autoloader.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/cypress.yml
  .github/workflows/jest.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/relativeci.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: tests, 3. to review

#4346 feat: hide share and close buttons on direct editing for desktop
  cypress/e2e/directediting.spec.js
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/views/DirectEditing.vue
Labels: bug, 4. to release

#4401 fix: remove redundant css
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
Labels: 4. to release

#4406 chore: update relativeci workflow and webpack usage
  .github/workflows/node.yml
  .github/workflows/relativeci.yml
  .gitignore
  package.json
  webpack.config.js
Labels: 4. to release, technical debt

#4412 ci(cypress): Adapt modal selector to viewer change
  cypress/e2e/nodes/Links.spec.js
  cypress/e2e/viewer.spec.js
Labels: bug, tests, 3. to review

#4411 chore(ci): Run cypress against proper stable branch
  .github/workflows/cypress.yml
Labels: tests, 3. to review, bug: regression

#4409 fix(frontend): Update last saved timestamp when document is saved
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/services/SyncService.js
Labels: 3. to review, backport-request

#4413 ci(cypress): Revert show_hidden method for cypress interception
  cypress/support/commands.js
Labels: bug, tests, 3. to review

#4419 [stable25] fix: hotkey ctrl-s
  js/editor-rich.js
  js/editor-rich.js.map
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
Labels: bug, 4. to release
