Repository nextcloud/text, pull requests merged in 2023-10, with the labels that each got.

#4825 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4806 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4833 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4834 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4831 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4780 Fixes and additions to editor API
  src/components/Editor.vue
  src/components/Editor/MarkdownContentEditor.vue
  src/editor.js
Labels: bug, 3. to review

#4840 enh(editorApi): Introduce editor API version number
  src/editor.js
Labels: enhancement, 3. to review, backport-request

#4844 fix(editorApi): Use attachment resolver in MarkdownContentEditor
  src/components/Editor/MarkdownContentEditor.vue
  src/editor.js
Labels: 3. to review, backport-request

#4836 enh(SyncService): Throw error on save failure
  src/services/SyncService.js
Labels: enhancement, 3. to review

#4846 ci(cypress): Fix failing cypress spec by more specific selector
  cypress/support/commands.js
Labels: bug, 3. to review

#4848 [stable26] fix(editorApi): Use attachment resolver in MarkdownContentEditor
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/MarkdownContentEditor.vue
  src/editor.js
Labels: 3. to review

#4847 ci(cypress): Use cypress-split for running tests in parallel
  .github/workflows/cypress.yml
  cypress.config.js
  cypress/e2e/nodes/CodeBlock.spec.js
  package-lock.json
  package.json
Labels: 3. to review

#4869 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4877 fix(paste): paste plaintext with separate paragraphs
  src/extensions/Markdown.js
Labels: backport-request

#4887 fix(readme): Clarify the dependency on the viewer app
  README.md
Labels: 3. to review

#4874 feat(MenuBar): Make the menu bar `role=toolbar` and add focus handling
  src/components/Menu/ActionEntry.js
  src/components/Menu/BaseActionEntry.js
  src/components/Menu/MenuBar.vue
  src/components/Menu/ReadonlyBar.vue
  src/components/Menu/ToolBarLogic.js
Labels: enhancement, 4. to release, ux

#4885 fix: Rename rich workspace to folder description
  src/views/FilesSettings.vue
Labels: bug, 3. to review

#4886 fix(makefile): Disable parallel execution of targets
  Makefile
Labels: 3. to review, technical debt

#4888 fix(menubar): Add aria-selected and aria-activedescendant to menu bar items (fix #3911)
  src/components/Menu/ActionList.vue
  src/components/Menu/utils.js
Labels: bug, 3. to review, accessibility

#4893 chore(dependencies): Bump @nextcloud/vue to 8.0.0-beta.9
  package-lock.json
Labels: dependencies, 3. to review

#4894 chore(php): Add PHP 8.3 to test matrix
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
Labels: 3. to review, technical debt

#4872 fix(paste): collapse whitespace before pasting
  src/extensions/Markdown.js
  src/extensions/transformPastedHTML.js
  src/tests/extensions/transformPastedHTML.spec.js
Labels: bug, 3. to review, backport-request

#4875 fix(mermaid): Only switch back on failure if in preview mode
  src/nodes/CodeBlockView.vue
Labels: bug, 3. to review, backport-request

#4901 fix line-through selector
  src/css/prosemirror.scss
Labels: bug, 4. to release, backport-request

#4868 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4870 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4892 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4808 Run cypress (in serial) in stable27 again
  .github/workflows/cypress.yml
Labels: 3. to review

#4903 Revert "ci: Skip some heading tests for now due to #4895"
  cypress/e2e/workspace.spec.js
Labels: tests, 3. to review

#4891 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4782 fix: deleting rich workspaces readme.md
  src/views/RichWorkspace.vue
Labels: bug, 4. to release

#4928 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4927 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4890 Use `@nextcloud/dialogs` v5 (required for FilePicker on Nextcloud 28+)
  cypress/e2e/nodes/Links.spec.js
  package-lock.json
  package.json
  src/components/Menu/ActionInsertLink.vue
  src/tests/setup.js
Labels: bug, 4. to release, dependencies: javascript

#4873 fix: Move new file action to F2V api
  cypress/e2e/workspace.spec.js
  package-lock.json
  package.json
  src/helpers/files.js
  src/tests/__mocks__/css.js
  src/tests/__mocks__/svg.js
  webpack.config.js
Labels: tests, 3. to review

#4824 Fix 403 on close
  cypress/e2e/api/SessionApi.spec.js
  src/services/SessionApi.js
  src/services/SyncService.js
  src/services/WebSocketPolyfill.js
Labels: backport-request
