Repository nextcloud/text, pull requests merged in 2023-09, with the labels that each got.

#4764 [stable26] Update nextcloud/ocp dependency
  composer.lock
  cypress/e2e/nodes/Links.spec.js
Labels: dependencies, 3. to review

#4762 [main] Update nextcloud/ocp dependency
  composer.lock
  cypress/e2e/nodes/Links.spec.js
Labels: dependencies, 3. to review

#4763 [stable25] Update nextcloud/ocp dependency
  composer.lock
  cypress/e2e/links.spec.js
Labels: dependencies, 3. to review

#4765 [stable27] Update nextcloud/ocp dependency
  composer.lock
  cypress/e2e/nodes/Links.spec.js
Labels: dependencies, 3. to review

#4749 ci: Add workflow to update node dist files on main
  .github/workflows/node-dist-unchanged.yml
  .github/workflows/node.yml
  .github/workflows/update-node-dist.yml
  .gitignore
Labels: 3. to review, technical debt

#4721 fix: Use proper value for checking if editable
  cypress/e2e/nodes/CodeBlock.spec.js
  src/nodes/CodeBlockView.vue
Labels: bug, 3. to review, backport-request

#4771 feat: hide workspace if no readme.md
  src/views/RichWorkspace.vue
Labels: 3. to review

#4777 Change three dots to an ellipsis
  src/nodes/CodeBlockView.vue
Labels: bug, 4. to release

#4776 fix: Avoid layout jump with rich workspace
  composer.lock
  cypress/e2e/conflict.spec.js
  lib/Listeners/FilesLoadAdditionalScriptsListener.php
  src/files.js
  src/helpers/files.js
  src/init.js
  src/views/RichWorkspace.vue
  webpack.config.js
Labels: bug, 3. to review

#4310 Y.js backend enhancements and debug helpers
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  cypress/e2e/api/SessionApi.spec.js
  lib/Service/DocumentService.php
  lib/Service/SessionService.php
  lib/YjsMessage.php
  src/components/Editor.vue
  src/helpers/yjs.js
  src/services/WebSocketPolyfill.js
  tests/unit/YjsMessageTest.php
Labels: 3. to review, technical debt

#4788 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4789 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
