Repository nextcloud/text, pull requests merged in 2023-08, with the labels that each got.

#4520 fix: tab key in code block
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
Labels: bug, 3. to review

#4545 feat: add component SkeletonLoading
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/components/Editor/Wrapper.vue
  src/components/SkeletonLoading.vue
  src/views/RichWorkspace.vue
Labels: enhancement, 3. to review

#4621 fix(editor): Don't load both Tiptap collaboration history extensions
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/MarkdownContentEditor.vue
  src/extensions/RichText.js
Labels: 3. to review, backport-request, regression

#4642 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4644 fix: Use default font size
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/css/prosemirror.scss
Labels: bug, 3. to review

#4645 fix(css): Move code highlighting CSS to `prosemirror.scss`
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/css/prosemirror.scss
Labels: bug, 4. to release, backport-request

#4653 feat(npm): Prepare for 28.0.0-dev.1 release
  package.json
Labels: 3. to review

#4640 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4641 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4643 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4678 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4667 ci(cypress): Make sure to build before cypress
  .github/workflows/cypress.yml
Labels: bug, tests, 3. to review, backport-request

#4714 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4731 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4730 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4734 fix(cypress): close attachments file before proceeding
  cypress/e2e/attachments.spec.js
  cypress/support/commands.js
Labels: bug, tests, 2. developing

#4718 [stable23] Avoid loading the image before the node view
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/Image.js
Labels: bug, 4. to release

#4663 Cypress tests for smart picker, code block, mermaid and version view/compare
  cypress/e2e/SmartPicker.spec.js
  cypress/e2e/nodes/CodeBlock.spec.js
  cypress/e2e/versions.spec.js
  cypress/fixtures/codeblock.md
  cypress/support/commands.js
  cypress/support/e2e.js
  src/components/Suggestion/LinkPicker/suggestions.js
Labels: tests, 4. to release
