Repository nextcloud/text, pull requests merged in 2023-04, with the labels that each got.

#4021 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4036 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3999 fix: scroll for outline
  cypress/e2e/attachments.spec.js
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/EditorOutline.vue
  src/components/Editor/TableOfContents.vue
Labels: bug, 4. to release

#4028 fix: Properly emit ready event on conflicts with the editor API
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
Labels: bug, 3. to review, backport-request

#4053 fix: Only handle recent awareness messagess from sessions
  js/editor-collab.js
  js/editor-collab.js.map
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/SessionList.vue
  src/services/SyncService.js
Labels: bug, 3. to review, backport-request

#4061 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4074 [stable26] fix(cypress): show hidden files request now uses PUT
  cypress/support/commands.js
Labels: tests, 3. to review

#4076 fix(conflict): resolve quickly with fast sync.
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/CollisionResolveDialog.vue
  src/services/SyncService.js
Labels: bug, 4. to release, backport-request

#4071 fix: update ImageView
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/ImageView.vue
Labels: bug, 4. to release, backport-request

#4083 Add new text file action label
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/AppInfo/Application.php
  src/helpers/files.js
Labels: 3. to review, accessibility
