Repository nextcloud/text, pull requests merged in 2023-01, with the labels that each got.

#3631 fix(Images): Update image alt text on blur
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/nodes/ImageView.vue
Labels: bug, 3. to review

#3627 fix: reconnect - reload main container
  js/editor.js
  js/editor.js.LICENSE.txt
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/components/Editor/Status.vue
  src/mixins/refreshMoment.js
Labels: backport-request

#3650 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3665 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3663 perf: Add authorative autoloader
  .github/workflows/autoloader.yml
  .php-cs-fixer.dist.php
  Makefile
  composer/autoload.php
  composer/composer.json
  composer/composer.lock
  composer/composer/ClassLoader.php
  composer/composer/InstalledVersions.php
  composer/composer/LICENSE
  composer/composer/autoload_classmap.php
  composer/composer/autoload_namespaces.php
  composer/composer/autoload_psr4.php
  composer/composer/autoload_real.php
  composer/composer/autoload_static.php
  composer/composer/installed.json
  composer/composer/installed.php
Labels: 3. to review, performance 🚀

#3679 chore(ci): Fix merge freeze check for text
  .github/workflows/block-merge-freeze.yml
Labels: 3. to review

#3683 Always provide original GIF file
  lib/Service/AttachmentService.php
Labels: enhancement, 3. to review, feature: images

#3649 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3651 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3703 Fix bug when session not found
  lib/Controller/SessionController.php
Labels: bug, 3. to review

#3721 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3722 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
