Repository nextcloud/text, pull requests merged in 2023-07, with the labels that each got.

#4467 [stable27] Fix npm audit
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  package-lock.json
Labels: dependencies, 3. to review

#4465 [stable26] Fix npm audit
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  package-lock.json
Labels: dependencies, 3. to review

#4464 [main] Fix npm audit
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  package-lock.json
Labels: dependencies, 3. to review

#4466 [stable25] Fix npm audit
  js/editor.js
  js/editor.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  package-lock.json
Labels: dependencies, 3. to review

#4463 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4462 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4339 fix: Delete inactive sessions in one query
  lib/Db/SessionMapper.php
  tests/unit/Db/SessionMapperTest.php
Labels: bug, 3. to review

#4472 [stable27] fix: Delete inactive sessions in one query
  lib/Db/SessionMapper.php
  tests/unit/Db/SessionMapperTest.php
Labels: bug, 3. to review

#4473 [stable26] fix: Delete inactive sessions in one query
  lib/Db/SessionMapper.php
  tests/unit/Db/SessionMapperTest.php
Labels: bug, 3. to review

#4481 fix: Fetch attachment share permissions
  lib/Service/AttachmentService.php
Labels: bug, 3. to review, backport-request

#4474 Fix sync errors after network issues
  cypress/e2e/api/SyncServiceProvider.spec.js
  cypress/e2e/api/Yjs.spec.js
  cypress/e2e/sync.spec.js
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/services/PollingBackend.js
  src/services/SyncService.js
  src/services/SyncServiceProvider.js
  src/services/WebSocketPolyfill.js
Labels: bug, 2. developing, backport-request, bug: regression

#4486 [stable27] Fix sync errors after network issues
  cypress/e2e/api/SyncServiceProvider.spec.js
  cypress/e2e/api/Yjs.spec.js
  cypress/e2e/sync.spec.js
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/services/PollingBackend.js
  src/services/SyncService.js
  src/services/SyncServiceProvider.js
  src/services/WebSocketPolyfill.js
Labels: 4. to release, bug: regression

#4487 [stable26] Fix sync errors after network issues
  cypress/e2e/api/SyncServiceProvider.spec.js
  cypress/e2e/api/Yjs.spec.js
  cypress/e2e/sync.spec.js
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/services/PollingBackend.js
  src/services/SyncService.js
  src/services/SyncServiceProvider.js
  src/services/WebSocketPolyfill.js
Labels: 4. to release, bug: regression

#4489 [stable25] fix: Fetch attachment share permissions
  .github/workflows/cypress.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  js/editor.js.map
  lib/Service/AttachmentService.php
Labels: bug, 3. to review

#4490 [stable24] fix: Fetch attachment share permissions
  js/editor.js.map
  lib/Service/ImageService.php
Labels: bug, 3. to review

#4495 fix: remove duplicated save key action
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
Labels: bug, 3. to review, bug: regression

#4488 fix: Encode individual parts of the dav url as uri components
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/services/AttachmentResolver.js
  src/tests/services/AttachmentResolver.spec.js
Labels: bug, 3. to review

#4503 fix(sync): only save on close if changes were made
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/services/SyncService.js
Labels: bug, 3. to review, high

#4507 tests(cypress): Refactor reconnect test to be more reliable and add second test for actual reconnect
  cypress/e2e/sync.spec.js
Labels: tests, 3. to review, backport-request

#4496 Fix some JS deprecations
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor/Status.vue
  src/helpers/mime.js
Labels: 3. to review

#4521 fix: Add index to session_id on text_steps table
  composer.lock
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/AppInfo/Application.php
  lib/Listeners/AddMissingIndicesListener.php
  lib/Migration/Version010000Date20190617184535.php
Labels: bug, 3. to review, backport-request, high

#4539 fix: Use prefilter for delete with subquery
  lib/Db/SessionMapper.php
Labels: bug, 3. to review

#4540 fix: Remember cursor position when autofocus on load
  js/editor.js
  js/editor.js.LICENSE.txt
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/extensions/Autofocus.js
Labels: bug, 3. to review, backport-request

#4550 ci: Fix cypress test failing due to new autofocus cursor position
  cypress/e2e/sync.spec.js
Labels: 3. to review

#4549 fix: Use simple query and chunk in PHP to delete inactive sessions
  lib/Db/SessionMapper.php
Labels: bug, 3. to review, backport-request, high, regression

#4553 fix(postgres): Use a unique index name
  lib/Listeners/AddMissingIndicesListener.php
  lib/Migration/Version010000Date20190617184535.php
Labels: 3. to review, bug: regression

#4582 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4583 [stable25] Update nextcloud/ocp dependency
  composer.lock
  js/editor.js.map
Labels: dependencies, 3. to review

#4299 Feature/translate modal
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Menu/MenuBar.vue
  src/components/Modal/Translate.vue
Labels: enhancement, design, 3. to review

#4588 fix(mentions): encode user id in mentions URLs
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/highlight/q-js-js.js
  js/highlight/q-js-js.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/extensions/Mention.js
  src/tests/markdown.spec.js
  src/tests/markdownit.spec.js
Labels: backport-request

#4584 Stricter typing to match psalm level 2
  lib/Controller/AttachmentController.php
  lib/Controller/PublicSessionController.php
  lib/Controller/SessionController.php
  lib/Controller/SettingsController.php
  lib/Controller/UserApiController.php
  lib/Controller/WorkspaceController.php
  lib/Cron/Cleanup.php
  lib/Db/Document.php
  lib/Db/DocumentMapper.php
  lib/Db/Session.php
  lib/Db/SessionMapper.php
  lib/Db/Step.php
  lib/Db/StepMapper.php
  lib/Migration/Version010000Date20190617184535.php
  lib/Service/ApiService.php
  lib/Service/AttachmentService.php
  lib/Service/DocumentService.php
  lib/Service/EncodingService.php
  lib/Service/SessionService.php
  lib/Service/WorkspaceService.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review, technical debt

#4510 Fix save on direct editing
  cypress/e2e/directediting.spec.js
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/views/DirectEditing.vue
Labels: bug, 3. to review, regression

#4336 Fade out user cursor labels after five seconds of inactivity
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/highlight/q-js-js.js
  js/highlight/q-js-js.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/extensions/CollaborationCursor.js
  src/extensions/index.js
  src/services/SyncService.js
Labels: bug, 3. to review, backport-request

#4596 fix(css): Fix margin-bottom for list items
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/css/prosemirror.scss
Labels: 3. to review, bug: regression

#4612 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4611 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4424 Split sync of ApiService to sync and save
  appinfo/routes.php
  cypress/e2e/api/SessionApi.spec.js
  cypress/e2e/sync.spec.js
  cypress/support/sessions.js
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  lib/Controller/PublicSessionController.php
  lib/Controller/SessionController.php
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  src/services/PollingBackend.js
  src/services/SessionApi.js
  src/services/SyncService.js
Labels: enhancement, 2. developing
