Repository nextcloud/text, pull requests merged in 2023-11, with the labels that each got.

#4942 chore(DocumentService): Several code style fixes
  lib/Service/DocumentService.php
Labels: 3. to review, technical debt

#4964 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4945 fix(menubar): Code style fixes
  src/components/Menu/MenuBar.vue
  src/components/Menu/ReadonlyBar.vue
  src/components/Menu/ToolBarLogic.js
Labels: bug, 3. to review

#4938 fix(sync): prevent race condition by relying on autoincrement
  cypress/e2e/api/SessionApi.spec.js
  lib/Db/Step.php
  lib/Db/StepMapper.php
  lib/Service/DocumentService.php
Labels: bug, 3. to review, feature: sync

#4970 [stable27] fix(sync): prevent race condition by relying on autoincrement
  cypress/e2e/SessionApi.spec.js
  lib/Db/Step.php
  lib/Db/StepMapper.php
  lib/Service/DocumentService.php
Labels: 3. to review, backport-request

#4971 fix(codeblock): Display mermaid graph per default in readonly mode
  src/nodes/CodeBlockView.vue
Labels: bug, feature: formatting, 3. to review

#4994 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4996 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4995 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4997 fix: Limit asset/source loader rule to inline svg embeddings from @mdi/svg
  webpack.config.js
Labels: bug, 3. to review

#4965 feat: bring back cypress command createDescription through UI
  cypress/support/commands.js
  src/components/Menu/ActionList.vue
  src/helpers/files.js
  src/init.js
  src/views/RichWorkspace.vue
Labels: 3. to review

#4990 [stable26] fix(SyncService): handle failing connection gracefully
  js/editor.js
  js/editor.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/services/SyncService.js
Labels: bug, 4. to release

#4998 fix: Add migration to drop conflicting index ts_session
  appinfo/info.xml
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/Migration/Version030901Date20231114150437.php
Labels: bug, 4. to release

#5006 chore: Bump @nextcloud/vue to v8.2.0
  package-lock.json
  package.json
Labels: 3. to review

#5015 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5017 fix: Get file from share link instead of user directory in case of no access
  lib/Service/DocumentService.php
Labels: bug, 3. to review

#5020 fix(ImageView): Fix detection of editable editor
  src/nodes/ImageView.vue
Labels: bug, backport-request, ux

#5022 fix: bring back rich workspace on public share links of folders
  src/public.js
Labels: 3. to review

#5021 Rich workspace polishing
  src/helpers/files.js
  src/views/RichWorkspace.vue
Labels: bug, 3. to review

#5016 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5040 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5039 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5041 Create update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: 3. to review

#5046 Fix typo in author comment
  lib/Migration/Version030901Date20231114150437.php
Labels: 3. to review

#4959 Revert "ci: Skip failing link to directory test"
  cypress/e2e/nodes/Links.spec.js
Labels: tests, 3. to review, backport-request

#4698 Lazy load text-viewer and text-files
  src/files.js
  src/helpers/files.js
  src/viewer.js
  webpack.config.js
Labels: 3. to review, performance 🚀, javascript

#5058 ci: Move server version to the actual build step
  .github/workflows/cypress.yml
Labels: bug, 3. to review

#5057 [stable28] Run cypress against stable28 branch
  .github/workflows/cypress.yml
Labels: bug, 3. to review

#5063 fix: Hide cursor in print output
  cypress/e2e/print.spec.js
  cypress/snapshots/base/print.spec.js/print view in single-file share.png
  cypress/snapshots/base/print.spec.js/print view in viewer.png
  src/css/print.scss
Labels: bug, 3. to review

#5064 [stable28] fix(css): Fix print view in viewer and single-file share
  .github/workflows/cypress.yml
  .gitignore
  cypress.config.js
  cypress/e2e/print.spec.js
  cypress/fixtures/print.md
  cypress/snapshots/base/print.spec.js/print view in single-file share.png
  cypress/snapshots/base/print.spec.js/print view in viewer.png
  cypress/support/commands.js
  package-lock.json
  package.json
  src/components/RichTextReader.vue
  src/css/print.scss
Labels: 3. to review, bug: regression

#4904 Revert "tmp: skip known attachment failures"
  cypress/e2e/attachments.spec.js
  cypress/e2e/nodes/ImageView.spec.js
  cypress/support/commands.js
Labels: tests, 3. to review
