Repository nextcloud/text, pull requests merged in 2024-08, with the labels that each got.

#6166 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6164 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6158 ci(cypress): Adapt to file name link being a button now
  cypress/support/commands.js
Labels: tests, 3. to review

#6145 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6167 fix: Avoid throwing in BeforeNodeWrittenListener on new files
  lib/Listeners/BeforeNodeWrittenListener.php
Labels: bug, 3. to review

#6168 chore(deps): Upgrade cypress to 13.6.4
  package-lock.json
  package.json
Labels: tests, 3. to review

#6141 [main] Update nextcloud/ocp dependency
  composer.lock
  tests/psalm-baseline.xml
Labels: dependencies, 3. to review

#6178 fix: Move settings to use NcCheckboxRadioSwitch
  src/views/FilesSettings.vue
Labels: bug, 3. to review

#6179 ci: Fix selector for viewer modal name
  cypress/e2e/nodes/Links.spec.js
  cypress/e2e/viewer.spec.js
Labels: bug, 3. to review

#6132 [Assistant] Add button in task result
  src/components/Assistant.vue
Labels: enhancement, 2. developing

#6177 chore: Add migration attributes
  composer.json
  composer.lock
  lib/Migration/Version040100Date20240611165300.php
Labels: enhancement, 3. to review

#6181 fix: Only insert smart picker result as preview if it is a valid URL
  src/components/Suggestion/LinkPicker/suggestions.js
Labels: bug, 3. to review

#6199 feat: Move search highlighting to editor API
  cypress/component/editor/search.cy.js
  cypress/fixtures/lorem.txt
  src/editor.js
  src/extensions/Search.js
  src/plugins/searchDecorations.js
  src/tests/plugins/searchQuery.spec.js
Labels: enhancement, 2. developing, javascript

#6196 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6194 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6211 fix(attachments): Uploading of attachments from public shares
  lib/Controller/AttachmentController.php
  src/components/Editor/MediaHandler.vue
  src/services/SessionApi.js
Labels: bug, 3. to review, backport-request

#6236 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6217 fix: Ensure WebsocketPolyfill always has the latest session state and version
  src/components/Editor.vue
  src/services/SyncService.js
  src/services/WebSocketPolyfill.js
  src/tests/services/WebsocketPolyfill.spec.js
Labels: bug

#6243 fix: catch all errors when getting rich workspace content
  lib/DAV/WorkspacePlugin.php
Labels: 3. to review, backport-request

#6250 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
Labels: dependencies, 3. to review, automated

#6238 [stable30] Fix npm audit
  js/vendor.LICENSE.txt
  package-lock.json
Labels: dependencies, 3. to review

#6265 ci(cypress): Fix file list link selector
  cypress/support/commands.js
Labels: bug, tests, 3. to review, backport-request

#6268 fix(ViewerComponent): use MarkdownContentEditor for readonly views
  cypress/e2e/versions.spec.js
  src/components/Editor/MarkdownContentEditor.vue
  src/components/ViewerComponent.vue
Labels: bug, 3. to review, feature: embed

#6195 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6239 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6251 feat(editor): Add support for collapsible sections
  cypress/e2e/nodes/Details.spec.js
  package-lock.json
  package.json
  src/components/Editor/PreviewOptions.vue
  src/components/Menu/entries.js
  src/components/icons.js
  src/extensions/RichText.js
  src/markdownit/details.ts
  src/markdownit/index.js
  src/nodes/CodeBlockView.vue
  src/nodes/Details.js
  src/nodes/DetailsContent.js
  src/nodes/DetailsContent.vue
  src/nodes/DetailsSummary.js
  src/nodes/DetailsView.vue
  src/tests/markdown.spec.js
  src/tests/markdownit/details.spec.js
Labels: feature: formatting, 3. to review

#6197 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6274 fix(editorApi): Add support for a onCreate callback that gets content
  src/components/Editor.vue
  src/editor.js
Labels: 3. to review, backport-request, integration

#6271 fix(attachments): Show proper error message at upload error
  lib/Controller/AttachmentController.php
  lib/Service/AttachmentService.php
  src/components/Editor/MediaHandler.vue
Labels: 3. to review, backport-request

#6283 fix: hide menu Link to file for direct editing
  src/components/Menu/ActionInsertLink.vue
Labels: bug, 3. to review

#6282 Allow viewing of attachments when shared by mail
  lib/Service/AttachmentService.php
Labels: bug, 3. to review
