Repository nextcloud/text, pull requests merged in 2024-01, with the labels that each got.

#5193 Fix/5080 keep menubar in workspace
  src/components/Editor.vue
  src/components/Menu/MenuBar.vue
  src/views/RichWorkspace.vue
Labels: 3. to review, backport-request, accessibility

#5174 feat: switch to native browser tooltips
  src/components/Editor/GuestNameDialog.vue
  src/components/Editor/SessionList.vue
  src/components/Editor/Status.vue
  src/components/HelpModal.vue
  src/components/Menu/ActionAttachmentUpload.vue
  src/components/Menu/ActionInsertLink.vue
  src/components/Menu/ActionList.vue
  src/components/Menu/BaseActionEntry.js
  src/components/Menu/EmojiPickerAction.vue
Labels: bug, 3. to review, accessibility

#5210 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5209 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5208 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5214 [stable26] Preserve queue during reconnects
  cypress/e2e/api/SyncServiceProvider.spec.js
  js/editor.js
  js/editor.js.map
  js/files-modal.js
  js/files-modal.js.map
  js/text-editors.js
  js/text-editors.js.map
  js/text-files.js
  js/text-files.js.map
  js/text-public.js
  js/text-public.js.map
  js/text-text.js
  js/text-text.js.map
  js/text-viewer.js
  js/text-viewer.js.map
  src/components/Editor.vue
  src/services/SyncServiceProvider.js
  src/services/WebSocketPolyfill.js
  src/tests/services/WebsocketPolyfill.spec.js
Labels: 3. to review

#5224 fix: Skip editor container and file upload input during keyboard navigation
  src/components/Editor.vue
  src/components/Editor/MediaHandler.vue
Labels: bug, 3. to review, backport-request, accessibility

#5226 fix: Prioritize un-collapsible menubar entries for mobile and aggregate children in the hidden entries
  src/components/Menu/MenuBar.vue
  src/components/Menu/entries.js
Labels: bug, 3. to review, backport-request, accessibility

#5229 fix: Only show translate if providers are available
  src/components/Menu/MenuBar.vue
Labels: bug, 3. to review, backport-request

#5230 fix: Use proper way of hiding the attachment input
  src/components/Editor/MediaHandler.vue
Labels: bug, 3. to review, backport-request, accessibility

#5233 Fix migration from `v-tooltip` to native `title` in menu bar buttons `ActionEntry`
  src/components/Menu/ActionSingle.vue
  src/components/Suggestion/SuggestionListWrapper.vue
  src/nodes/Table/TableCellView.vue
  src/nodes/Table/TableHeaderView.vue
  src/nodes/Table/TableView.vue
Labels: bug, 3. to review, backport-request, technical debt

#5254 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5255 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5263 [stable26] Approve and merge ocp updates
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: tests

#5262 [stable27] Approve and merge ocp updates
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: tests

#5212 fix: Properly copy selection as markdown to the plaintext clipboard
  src/EditorFactory.js
  src/components/Editor.vue
  src/extensions/Markdown.js
  src/tests/plaintext.spec.js
Labels: bug, 3. to review

#5267 fix(psalm): getPassword may return null
  lib/Controller/PublicSessionController.php
Labels: bug, 3. to review, php

#5274 [stable26] fix: Proper error message based on file permissions
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  tests/unit/Service/DocumentServiceTest.php
Labels: bug, 3. to review

#5272 [stable28] fix: Proper error message based on file permissions
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  src/components/Editor.vue
  tests/unit/Service/DocumentServiceTest.php
Labels: bug, 3. to review

#5275 [stable25] fix: Proper error message based on file permissions
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  tests/unit/Service/DocumentServiceTest.php
Labels: bug, 3. to review

#5271 fix: Proper error message based on file permissions
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  src/components/Editor.vue
  tests/unit/Service/DocumentServiceTest.php
Labels: bug, 3. to review

#5276 [stable24] fix: Proper error message based on file permissions
  js/editor.js.map
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  tests/unit/Service/DocumentServiceTest.php
Labels: bug, 3. to review

#5277 [stable23] fix: Proper error message based on file permissions
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
  tests/unit/Service/DocumentServiceTest.php
Labels: bug, 3. to review

#5278 fix(package): indentation to be 2 spaces as elsewhere
  package.json
Labels: 3. to review

#5279 fix(sync): push local changes on reconnect
  .github/workflows/cypress-component.yml
  cypress.config.js
  cypress/component/helpers/yjs.cy.js
  cypress/component/upstream/Yjs.cy.js
  cypress/support/component-index.html
  cypress/support/component.js
  lib/Service/DocumentService.php
  package-lock.json
  package.json
  src/components/Editor.vue
  src/helpers/yjs.js
Labels: bug, 2. developing

#5312 fix: register viewer by uniq name instead of "component"
  src/viewer.js
Labels: 3. to review, technical debt

#5197 fix: translate popup does not open in mobile apps
  lib/DirectEditing/TextDirectEditor.php
  lib/Service/InitialStateProvider.php
Labels: bug, 3. to review

#5300 [main] Update nextcloud/ocp dependency
  composer.lock
  lib/Migration/ResetSessionsBeforeYjs.php
  lib/Service/ConfigService.php
Labels: dependencies, 3. to review

#5234 feat: add labels to textarea elements in translate modal
  src/components/Modal/Translate.vue
Labels: enhancement, 3. to review

#5317 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5281 fix: Fix tab focus when other elements are displayed next to text that are within a focus trap
  src/EditorFactory.js
  src/components/Editor.vue
  src/components/Editor/ContentContainer.vue
  src/extensions/FocusTrap.js
  src/extensions/index.js
  src/nodes/CodeBlockView.vue
Labels: bug, 2. developing, accessibility

#5158 Link bubble menu to preview and edit links
  cypress/e2e/nodes/Links.spec.js
  cypress/e2e/workspace.spec.js
  src/components/Editor.provider.js
  src/components/Editor/MarkdownContentEditor.vue
  src/components/Link/LinkBubbleView.vue
  src/components/RichTextReader.vue
  src/css/prosemirror.scss
  src/editor.js
  src/extensions/LinkBubble.js
  src/extensions/LinkBubblePluginView.js
  src/extensions/RichText.js
  src/helpers/links.js
  src/marks/Link.js
  src/mixins/CopyToClipboardMixin.js
  src/nodes/Paragraph.js
  src/nodes/ParagraphView.vue
  src/plugins/link.js
  src/tests/nodes/Table.spec.js
  src/tests/tiptap.spec.js
Labels: enhancement, 3. to review
