Repository nextcloud/text, pull requests merged in 2024-12, with the labels that each got.

#6725 fix(eslint): Fix linting javascript files, also lint typescript files
  .eslintrc.cjs
  package.json
  src/global.d.ts
  src/markdownit/details.ts
  src/markdownit/taskLists.ts
  src/services/Outbox.ts
  src/vue-shim.d.ts
  tsconfig.json
Labels: tests, 3. to review, backport-request

#6729 fix(editor): Also unset `draggedOver` at drop
  src/components/Editor/MediaHandler.vue
Labels: bug, 3. to review, backport-request

#6733 fix(files): catch race condition in FilesWorkspaceHeader init
  src/helpers/files.js
Labels: bug, 3. to review, backport-request

#6728 fix(outline): fix mobile detection and box shadow
  src/components/Editor/EditorOutline.vue
  src/components/Editor/Wrapper.vue
Labels: bug, 3. to review, backport-request

#6720 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6737 Fix(debug): remove component in beforeDestroy hook
  src/components/Editor.vue
  src/helpers/debug.js
Labels: bug, 3. to review

#6750 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6767 chore: Bump composer files with new composer version
  composer/composer/InstalledVersions.php
  composer/composer/installed.php
Labels: 3. to review

#6539 fix(build): without non deterministic vendor-LICENSE.txt
  js/vendor.LICENSE.txt
  vite.config.ts
Labels: 3. to review, technical debt

#6427 feat: Migrate to files:node:updated
  package-lock.json
  package.json
  src/components/Editor.vue
  src/services/WebdavClient.ts
Labels: 3. to review

#6765 feat: Add support for `vite serve`
  README.md
  lib/Listeners/LoadEditorListener.php
  package.json
  vite.config.ts
Labels: 3. to review, technical debt, javascript

#6790 fix(licenses): SPDF license in package.json and khroma
  .github/workflows/reuse.yml
  LICENSES/BSD-2-Clause.txt
  LICENSES/BSD-3-Clause.txt
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/ISC.txt
  LICENSES/MPL-2.0.txt
  package.json
  vite.config.ts
Labels: 3. to review, backport-request

#4902 Feat/read only setting
  README.md
  cypress/e2e/openreadonly.spec.js
  cypress/support/commands.js
  lib/Service/ConfigService.php
  lib/Service/InitialStateProvider.php
  src/components/Editor.vue
  src/components/Editor/Wrapper.provider.js
  src/components/Editor/Wrapper.vue
  src/components/Menu/BaseActionEntry.js
  src/components/Menu/MenuBar.vue
  src/components/Menu/ReadonlyBar.vue
  src/components/Menu/entries.js
  src/components/Suggestion/LinkPicker/suggestions.js
  src/components/icons.js
  src/files.js
  src/public.js
Labels: enhancement, 3. to review, feedback-requested

#6721 [stable30] Fix npm audit
  LICENSES/BSD-3-Clause.txt
  LICENSES/EPL-2.0.txt
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/ISC.txt
  LICENSES/MPL-2.0.txt
  package-lock.json
Labels: dependencies, 3. to review

#6793 Add missing trailing slash in reverse proxy config docs
  README.md
Labels: bug, 3. to review, documentation

#6794 fix(link): Don't throw exception on invalid URL href
  src/marks/Link.js
Labels: bug, 3. to review, backport-request

#6800 Use "tertiary no background" as type for the buttons in table's header
  src/nodes/Table/TableHeaderView.vue
Labels: 3. to review

#6799 fix(files): switch action button to disabled state if results are empty
  src/components/Assistant.vue
Labels: 3. to review
