Repository nextcloud/text, pull requests merged in 2024-03, with the labels that each got.

#5422 Several link handling fixes
  src/components/Menu/ActionInsertLink.vue
  src/extensions/LinkBubblePluginView.js
  src/helpers/links.js
  src/marks/Link.js
  src/tests/helpers/links.spec.js
Labels: 3. to review, bug: regression

#5430 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5391 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5427 fix: Expose css var for maximum full size widgets
  src/components/Editor.vue
Labels: enhancement, 3. to review

#5399 Enh/preview links
  cypress/e2e/nodes/ListItem.spec.js
  cypress/e2e/nodes/Preview.spec.js
  cypress/e2e/nodes/helpers.js
  cypress/fixtures/Preview.md
  sample.md
  src/components/Editor/PreviewOptions.vue
  src/extensions/LinkBubblePluginView.js
  src/extensions/RichText.js
  src/helpers/links.js
  src/markdownit/index.js
  src/markdownit/preview.js
  src/marks/Link.js
  src/nodes/ParagraphView.vue
  src/nodes/Preview.js
  src/nodes/Preview.vue
  src/tests/markdown.spec.js
  src/tests/markdownit/preview.spec.js
  src/tests/nodes/Preview.spec.js
Labels: enhancement, 3. to review

#5439 fix: Disable nested embedding fully
  src/EditorFactory.js
  src/components/Editor.vue
  src/components/Link/LinkBubbleView.vue
  src/components/ViewerComponent.vue
  src/extensions/RichText.js
  src/nodes/Preview.js
  src/nodes/Preview.vue
Labels: bug, 3. to review

#5455 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5454 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5453 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5447 Fix cypress
  cypress/e2e/Assistant.spec.js
  cypress/e2e/workspace.spec.js
  package-lock.json
  package.json
Labels: tests, 3. to review

#5449 chore: update workflows from templates
  .github/workflows/cypress-component.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
Labels: dependencies, 3. to review, automated

#5464 test(ci): Revert some cypress workflow changes
  .github/workflows/cypress-e2e.yml
  .github/workflows/dependabot-approve-merge.yml
Labels: 3. to review

#5461 fix(Tables): require at least one cell in the header
  src/nodes/Table/TableHeadRow.js
Labels: 3. to review, backport-request

#5466 fix(backend): Accept pushs with only step1 messages by read-only clients
  .github/workflows/cypress-e2e.yml
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
Labels: 2. developing

#5469 fix(session): Fix setting a guest name
  cypress/e2e/share.spec.js
  src/components/Editor/GuestNameDialog.vue
  src/components/Editor/SessionList.vue
  src/components/Editor/Status.vue
  src/services/SessionApi.js
  src/services/SyncService.js
Labels: 3. to review, backport-request

#5470 fix: Avoid race condition that may initialize a document twice on the clients
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
Labels: bug, 3. to review

#5484 fix(attachments): Don't use currentSession for fetching attachments
  src/services/AttachmentResolver.js
  src/store/index.js
Labels: 3. to review, backport-request, feature: images

#5490 fix(LinkPicker): Don't open link picker inside code blocks
  src/extensions/LinkPicker.js
Labels: bug, 3. to review

#5491 chore(store): Remove unused currentSession from vuex store
  src/components/Editor.vue
  src/store/index.js
  src/store/mutation-types.js
Labels: 3. to review, technical debt

#5144 Bring back test failing due to server issue
  cypress/e2e/attachments.spec.js
Labels: backport-request, blocked

#5488 fix(HelpModal): Migrate to `NcDialog`, fix padding
  src/components/HelpModal.vue
Labels: design, 3. to review, bug: regression

#5512 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5497 fix: catch expected exception in event handler
  lib/Listeners/BeforeNodeWrittenListener.php
Labels: bug, 3. to review

#5511 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5513 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5514 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5498 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#5489 fix(MarkdownContentEditor): Respect `onLoaded` callback passed via API
  src/components/Editor/MarkdownContentEditor.vue
Labels: bug, 3. to review, backport-request

#5533 test(cypress): Downgrade cypress-io/github-action to v5.3.0 to fix errors
  .github/workflows/cypress-e2e.yml
Labels: 3. to review, technical debt

#5527 [stable27] chore(ci): Update Github workflows
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/cypress-component.yml
  .github/workflows/cypress-e2e.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/jest.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  cypress.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: 3. to review, technical debt

#5477 Ensure document stays consistent with y.js state file
  cypress/e2e/api/SessionApi.spec.js
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
Labels: bug, 3. to review

#5529 Fix/hide bubble when in menu
  cypress/e2e/nodes/Links.spec.js
  src/components/Editor/PreviewOptions.vue
  src/extensions/LinkBubble.js
  src/extensions/LinkBubblePluginView.js
  src/markdownit/preview.js
  src/nodes/ParagraphView.vue
  src/plugins/LinkBubblePluginView.js
  src/plugins/linkHelpers.js
  src/plugins/links.js
  src/tests/plugins/linkBubble.spec.js
Labels: 3. to review, 29 feedback

#5523 fix(sync): If `baseVersionEtag` changed, reset frontend
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  cypress/e2e/api/SessionApi.spec.js
  cypress/e2e/conflict.spec.js
  cypress/e2e/share.spec.js
  cypress/e2e/sync.spec.js
  cypress/support/sessions.js
  lib/Controller/PublicSessionController.php
  lib/Controller/SessionController.php
  lib/Exception/InvalidDocumentBaseVersionEtagException.php
  lib/Middleware/Attribute/RequireDocumentBaseVersionEtag.php
  lib/Middleware/SessionMiddleware.php
  lib/Service/ApiService.php
  src/components/Editor.vue
  src/components/Editor/DocumentStatus.vue
  src/services/PollingBackend.js
  src/services/SessionApi.js
  src/services/SyncService.js
Labels: 3. to review, feature: sync

#5538 fix(LinkBubble): Display link bubble view only if href is set
  src/components/Link/LinkBubbleView.vue
Labels: 3. to review, bug: regression

#5537 fix: Force visibility for tippy
  cypress/e2e/Assistant.spec.js
  src/css/prosemirror.scss
Labels: bug, 3. to review, high

#5545 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5540 fix(files): Change icons+wording for adding text doc and folder description
  cypress/support/commands.js
  img/article.svg
  lib/AppInfo/Application.php
  src/helpers/files.js
  src/public.js
Labels: 3. to review

#5547 fix: Use our own vue instance rendering anything but the viewer component
  src/ViewerVue.js
  src/components/Editor.singleton.js
  src/components/Editor/MarkdownContentEditor.vue
  src/components/ViewerComponent.vue
  src/plugins/LinkBubblePluginView.js
  src/plugins/linkHelpers.js
Labels: bug, 3. to review

#5566 fix(LinkBubble): Limit hide on scroll to div elements
  src/plugins/LinkBubblePluginView.js
Labels: 3. to review, bug: regression, 29 feedback

#5310 Remove bottom margin for better warning blocks display
  src/nodes/Callout.vue
Labels: design, 3. to review, backport-request

#5571 fix(links): set default for `loadState('core', 'active-app')`
  src/helpers/links.js
Labels: 3. to review, bug: regression

#5572 fix: Catch exceptions on non existing files
  lib/Listeners/BeforeNodeWrittenListener.php
Labels: bug, 3. to review

#5573 chore: Skip files list in sharing tests
  cypress/e2e/share.spec.js
Labels: tests, 3. to review

#5575 Feat/5524 link preview add button to delete links in preview mode
  cypress/e2e/nodes/PreviewOptions.spec.js
  src/components/Editor/PreviewOptions.vue
  src/nodes/ParagraphView.vue
  src/nodes/Preview.vue
Labels: enhancement, 2. developing

#5590 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
