Repository nextcloud/text, pull requests merged in 2024-09, with the labels that each got.

#6311 chore(CI): Updating renovate-approve-merge.yml workflow from template
  .github/workflows/renovate-approve-merge.yml
Labels: dependencies

#6307 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6291 fix: Correctly set "new"-menu entry for folder description
  .eslintrc.cjs
  src/helpers/files.js
Labels: bug, design, 3. to review, backport-request

#6306 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6309 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6287 [stable27] Ignore pushes of update steps for read only sessions
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/Service/DocumentService.php
  lib/Service/SessionService.php
  lib/YjsMessage.php
  tests/unit/YjsMessageTest.php
Labels: 3. to review

#6192 fix: Reuse NcAutoCompleteResult, remove code duplication
  src/components/Suggestion/Mention/AutoCompleteResult.vue
  src/components/Suggestion/Mention/MentionList.vue
Labels: bug, 2. developing, backport-request, technical debt

#6308 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6316 fix(Table): Fix pasting content with newlines to table cells
  src/nodes/Table/TableCell.js
Labels: bug, 3. to review, backport-request

#6315 fix(mention): No extra whitespace in markdown before/after mentions
  src/extensions/Mention.js
  src/tests/markdown.spec.js
Labels: bug, 3. to review, backport-request

#6333 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6334 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6338 Migrate reuse to toml format
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt

#6339 fix(public): Use `@nextcloud/sharing` to detect public shares
  cypress/e2e/nodes/CodeBlock.spec.js
  cypress/e2e/share.spec.js
  cypress/snapshots/base/print.spec.js/print view in single-file share.png
  cypress/support/commands.js
  package-lock.json
  package.json
  src/components/Editor.vue
  src/components/ViewerComponent.vue
  src/helpers/files.js
  src/helpers/token.js
  src/public.js
  src/views/RichWorkspace.vue
Labels: tests, 3. to review

#6323 fix(TaskList): Add class name to rendered HTML
  cypress/e2e/shortcuts.spec.js
  cypress/e2e/workspace.spec.js
  src/nodes/TaskItem.js
  src/nodes/TaskList.js
  src/tests/tiptap.spec.js
Labels: bug, 3. to review

#6345 fix: Reset session if file rename changes mimetype from/to markdown
  cypress/e2e/changeMimetype.spec.js
  lib/Listeners/BeforeNodeRenamedListener.php
Labels: bug, 3. to review, backport-request

#6336 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6335 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6346 fix(CodeBlock): Fix visibleFocus and pasting in code blocks
  src/nodes/CodeBlockView.vue
Labels: 3. to review, backport-request

#6337 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6374 test(cy): Fix ImageView native tests
  cypress/e2e/nodes/ImageView.spec.js
Labels: tests, 3. to review, backport-request, regression

#6378 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6365 test(ci): Fix path of visual regression base files
  cypress.config.mjs
  cypress/snapshots/base/cypress/e2e/print.spec.js/print view in single-file share.png
  cypress/snapshots/base/cypress/e2e/print.spec.js/print view in viewer.png
Labels: 3. to review

#6404 Fix headings papercuts
  src/components/Menu/MenuBar.vue
  src/components/Menu/ReadonlyBar.vue
  src/css/style.scss
Labels: bug, 3. to review, backport-request, bug: regression, design: papercut

#6353 feat(menu): Put list items in submenu, add indentation options
  cypress/e2e/workspace.spec.js
  src/components/Menu/ActionListItem.vue
  src/components/Menu/ActionSingle.vue
  src/components/Menu/BaseActionEntry.js
  src/components/Menu/entries.js
  src/components/Menu/utils.js
  src/components/Suggestion/LinkPicker/suggestions.js
  src/components/icons.js
  src/extensions/RichText.js
  src/nodes/BulletList.js
  src/nodes/OrderedList.js
  src/nodes/TaskList.js
Labels: bug, 3. to review

#6413 fix(placeholder): Show placeholder on empty paragraph, improve wording
  src/css/prosemirror.scss
  src/extensions/RichText.js
Labels: bug, design, 3. to review

#6423 feat: add nfo file support
  lib/DirectEditing/TextDirectEditor.php
  src/helpers/mime.js
Labels: enhancement, 3. to review

#6446 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6447 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6445 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6448 fix(css): Use singlequotes to please stylelint
  src/nodes/Preview.vue
Labels: 3. to review, backport-request

#6454 fix(details): Add margin-bottom
  src/nodes/DetailsView.vue
Labels: bug, 3. to review, design: papercut

#6453 fix(codeblock): Add border radius
  src/nodes/CodeBlockView.vue
Labels: bug, 3. to review, backport-request, design: papercut

#6456 [stable30] fix(codeblock): Add border radius
  src/nodes/CodeBlockView.vue
Labels: bug, 3. to review, backport-request, papercut

#6455 fix(tasklist): Correct indention
  src/css/prosemirror.scss
Labels: 3. to review, backport-request, bug: regression, design: papercut

#6452 fix(vite): set `NODE_ENV` in `package.json` scripts
  package.json
Labels: bug, 3. to review, backport-request

#6411 feat: restructure menubar #2
  cypress/e2e/workspace.spec.js
  src/components/Menu/ActionList.vue
  src/components/Menu/entries.js
  src/components/Menu/utils.js
  src/components/Suggestion/LinkPicker/suggestions.js
  src/components/icons.js
Labels: enhancement, design, 3. to review

#6461 [stable29] perf: optimize WorkspaceService::getFile
  lib/Service/WorkspaceService.php
Labels: 3. to review, performance 🚀
