Repository nextcloud/text, pull requests merged in 2024-10, with the labels that each got.

#6476 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6477 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6475 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6485 fix: Apply checks on shares in the middleware
  lib/Middleware/SessionMiddleware.php
Labels: backport-request

#6486 Check link protocol
  cypress/e2e/directediting.spec.js
  cypress/e2e/nodes/CodeBlock.spec.js
  cypress/e2e/nodes/Links.spec.js
  cypress/e2e/sections.spec.js
  cypress/e2e/sync.spec.js
  cypress/e2e/viewer.spec.js
  cypress/support/commands.js
  src/components/Link/LinkBubbleView.vue
  src/marks/Link.js
  src/tests/helpers/links.spec.js
Labels: backport-request

#6490 fix(sync): handle 502 (Bad Gateway) gracefully
  src/services/PollingBackend.js
Labels: backport-request

#6509 chore: Fix renovate config
  renovate.json
Labels: bug

#6507 Fix(plaintext): multiple linebreaks at end
  cypress/e2e/nodes/Links.spec.js
  src/EditorFactory.js
  src/components/Editor.vue
  src/mixins/setContent.js
  src/tests/builders.js
  src/tests/helpers.js
  src/tests/markdown.spec.js
  src/tests/nodes/Table.spec.js
  src/tests/plaintext.spec.js
  src/tests/tiptap.spec.js
Labels: bug, 3. to review, 28 feedback

#6514 [stable26] fix: Apply checks on shares in the middleware
  .github/workflows/cypress.yml
  lib/Service/AttachmentService.php
Labels: backport-request

#6474 [main] Update nextcloud/ocp dependency
  composer.lock
  lib/Notification/Notifier.php
Labels: dependencies, 3. to review

#6516 ci: Fix assistant button selector
  cypress/e2e/Assistant.spec.js
Labels: tests, 3. to review

#6520 feat: Increase line width to 80 characters
  src/css/variables.scss
Labels: enhancement, design, 3. to review

#6500 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6498 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6536 fix(tsconfig): only have one tsconfig file
  .tsconfig.json
Labels: 3. to review

#6535 enh(make): clean-git even if js or css directory do not exist
  Makefile
Labels: 3. to review

#5821 Use vitest instead of jest
  package-lock.json
  package.json
  renovate.json
  src/components/Menu/keys.js
  src/global.d.ts
  src/nodes/Paragraph.d.ts
  src/nodes/Paragraph.js
  src/tests/__mocks__/css.js
  src/tests/__mocks__/svg.js
  src/tests/extensions/Markdown.spec.js
  src/tests/helpers/links.spec.js
  src/tests/markdown.spec.js
  src/tests/marks/Underline.spec.js
  src/tests/nodes/Preview.spec.js
  src/tests/nodes/Table.spec.js
  src/tests/nodes/TaskItem.spec.js
  src/tests/plugins/extractHeadings.spec.js
  src/tests/plugins/extractLinkParagraphs.spec.js
  src/tests/plugins/searchDecorations.spec.js
  src/tests/services/AttachmentResolver.spec.js
  src/tests/services/WebsocketPolyfill.spec.js
  src/tests/setup.mjs
  src/tests/testHelpers/builders.js
  src/tests/testHelpers/createCustomEditor.ts
  src/tests/testHelpers/jsdomMocks.js
  src/tests/testHelpers/markdown.js
  src/tests/testHelpers/nextcloudMocks.js
  src/vue-shim.d.ts
  vite.config.ts
Labels: dependencies, 3. to review

#6501 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6508 [stable30] Fix(plaintext): multiple linebreaks at end
  src/EditorFactory.js
Labels: 3. to review

#6554 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6566 fix CODEOWNERS
  .github/CODEOWNERS
Labels: 3. to review

#6560 feat(editorApi): Add function to allow setting readonly bar props
  src/editor.js
Labels: enhancement, 3. to review

#6499 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6575 fix(mermaid): No custom link handling for links in mermaid diagrams
  src/plugins/links.js
Labels: bug, 3. to review, backport-request
