Repository nextcloud/text, pull requests merged in 2024-04, with the labels that each got.

#5564 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5563 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5592 chore: Update renovate.json to match stable releases
  renovate.json
Labels: 3. to review

#5591 fix: workspace tables expand correctly
  src/views/RichWorkspace.vue
Labels: bug, 3. to review

#5579 fix: Make edit mode in interactive widgets opt-in
  src/components/Editor.vue
  src/components/ViewerComponent.vue
Labels: bug, 3. to review, backport-request

#5601 test(cypress): Wait for syncs after opening+editing in in `sync.spec.js`
  cypress/e2e/sync.spec.js
Labels: tests, 3. to review

#5378 Cleanup `_oc_webroot` stubs where possible
  cypress/e2e/api/SessionApi.spec.js
  cypress/e2e/api/SyncServiceProvider.spec.js
  cypress/e2e/api/UsersApi.spec.js
  cypress/support/sessions.js
  src/tests/services/AttachmentResolver.spec.js
  src/tests/setup.js
Labels: tests, 3. to review

#5521 fix(LinkBubble): Treat links to hashes in same page directly
  src/helpers/links.js
  src/nodes/Preview.js
  src/plugins/linkHelpers.js
  src/plugins/links.js
Labels: bug, 3. to review, backport-request, 29 feedback

#5644 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5645 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5647 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5646 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5648 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5655 fix(imageview): Don't try to load unresolved images
  src/nodes/ImageView.vue
Labels: bug, 3. to review, backport-request, feature: embed

#5654 fix: improve node and mark copy-paste behavior
  src/extensions/Markdown.js
  src/tests/extensions/Markdown.spec.js
Labels: 3. to review, backport-request, bug: regression, format: markdown

#5659 fix: Avoid throwing when a workspace file cannot be found due to a failed storage
  lib/Service/WorkspaceService.php
Labels: bug, 3. to review

#5681 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5682 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5686 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5685 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5684 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5683 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5691 fix(links): 5539 close link bubble on click outside
  cypress/e2e/nodes/Links.spec.js
  src/plugins/LinkBubblePluginView.js
Labels: 3. to review, backport-request

#5696 fix(l10n): "Connection failed" not translatable
  src/components/Editor.vue
Labels: bug, 3. to review, backport-request

#5701 feat: disable spellcheck inside code blocks
  src/nodes/CodeBlockView.vue
Labels: 3. to review

#5715 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5723 fix(linkBubble): load only when needed
  package-lock.json
  src/plugins/LinkBubblePluginView.js
  src/tests/nodes/TaskItem.spec.js
Labels: 3. to review

#5630 fix: focus issue on translate modal, remove duplicate code
  cypress/e2e/Assistant.spec.js
  cypress/e2e/share.spec.js
  src/components/Assistant.vue
  src/components/Editor.vue
  src/components/Menu/MenuBar.vue
  src/components/Modal/Translate.vue
Labels: bug, 3. to review

#5732 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5729 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#5730 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#5734 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
