Repository nextcloud/text, pull requests merged in 2024-11, with the labels that each got.

#6574 fix(css): Set page `size: auto` instead of `size: A4`
  src/css/print.scss
Labels: bug, 3. to review, backport-request

#6597 Fix some JS console errors
  src/components/Assistant.vue
  src/components/Editor.vue
  src/components/Modal/Translate.vue
Labels: bug, 3. to review, backport-request

#6601 test(cypress): More specific selector for viewer header in links test
  cypress/e2e/nodes/Links.spec.js
Labels: bug, tests, 3. to review, backport-request

#6602 fix(addContent): only process addExtensions once
  src/mixins/setContent.js
Labels: backport-request

#6598 feat(debug): Expose yjs debug function in editor API
  src/components/Editor.vue
  src/editor.js
Labels: enhancement, 3. to review, backport-request

#6609 fix(files): set focus on image description right after inserting
  src/nodes/ImageView.vue
Labels: 3. to review

#6605 [stable30] fix(addContent): only process addExtensions once
  src/mixins/setContent.js
Labels: bug, 3. to review, backport-request

#6596 [stable29] fix(mermaid): No custom link handling for links in mermaid diagrams
  src/plugins/links.js
Labels: bug, 3. to review

#6614 fix(files): Align vertically bottons in code block
  src/nodes/CodeBlockView.vue
Labels: 3. to review

#6644 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6557 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6668 Revert "fix(css): Set page `size: auto` instead of `size: A4`"
  src/css/print.scss
Labels: 3. to review, backport-request, regression

#6675 fix: log ignored workspace propfind exceptions at debug
  lib/DAV/WorkspacePlugin.php
Labels: bug, 3. to review, backport-request

#6690 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6701 ci: Run cypress on ubuntu-latest
  .github/workflows/cypress-e2e.yml
  cypress/snapshots/base/cypress/e2e/print.spec.js/print view in single-file share.png
  cypress/snapshots/base/cypress/e2e/print.spec.js/print view in viewer.png
Labels: 3. to review, backport-request

#6569 feat: Add toggle for editor line length per user
  lib/Controller/SettingsController.php
  lib/Service/ConfigService.php
  lib/Service/InitialStateProvider.php
  src/components/Editor.vue
  src/components/Editor/SessionList.vue
  src/components/Editor/Status.vue
Labels: enhancement, 3. to review, feedback-requested

#6694 feat: render text inserted from assistant
  src/components/Assistant.vue
  src/components/Suggestion/LinkPicker/suggestions.js
  src/markdownit/hasMarkdownSyntax.js
  src/markdownit/isValidMarkdown.js
  src/markdownit/shouldInterpretAsMarkdown.js
Labels: bug, 3. to review

#6699 fix: catch all errors when getting rich workspace file
  lib/DAV/WorkspacePlugin.php
Labels: 3. to review, backport-request

#6706 [stable29] fix: catch all errors when getting rich workspace file
  lib/DAV/WorkspacePlugin.php
Labels: 3. to review
