Repository nextcloud/text, pull requests merged in 2024-07, with the labels that each got.

#5976 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5979 fix(attachments): Don't require document session for getting attachments
  lib/Controller/AttachmentController.php
  lib/Controller/ISessionAwareController.php
  lib/Controller/TSessionAwareController.php
  lib/Middleware/SessionMiddleware.php
Labels: bug, 3. to review, backport-request

#5982 [stable28] Revert "chore(deps): update cypress"
  package-lock.json
  package.json
Labels: tests, 3. to review, bug: regression

#5941 Keep base version etag during reload
  cypress/e2e/sync.spec.js
  src/components/Editor.vue
  src/components/Editor/GuestNameDialog.vue
  src/helpers/yjs.js
  src/services/PollingBackend.js
  src/services/SessionApi.js
  src/services/SyncService.js
  src/services/WebSocketPolyfill.js
Labels: bug, 2. developing, backport-request

#5989 fix: Change search highlight color and border radius
  src/plugins/searchDecorations.js
Labels: design, 3. to review

#5990 fix: Use css vars to adapt to new clickable area size
  src/components/Editor.vue
  src/components/Editor/SessionList.vue
  src/components/Editor/Status.vue
  src/components/Menu/ActionEntry.scss
  src/components/Menu/MenuBar.vue
  src/components/Suggestion/SuggestionListWrapper.vue
  src/css/prosemirror.scss
  src/nodes/ImageView.vue
  src/nodes/Preview.js
  src/views/DirectEditing.vue
  src/views/RichWorkspace.vue
Labels: bug, design, 3. to review

#5992 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#6019 fix(ApiService): Catch NotPermittedException and return 404
  lib/Service/ApiService.php
  lib/Service/DocumentService.php
Labels: 3. to review, backport-request

#6018 chore(editor): Remove obsolete code for author annotations
  cypress/e2e/nodes/Preview.spec.js
  cypress/e2e/nodes/helpers.js
  src/components/Editor.vue
  src/components/Editor/SessionList.vue
  src/components/Editor/Wrapper.vue
  src/nodes/Preview.js
  src/store/index.js
  src/store/mutation-types.js
Labels: 3. to review, technical debt

#6024 fix(vite): dedupe vue to only use one version of it
  vite.config.ts
Labels: 3. to review, bug: regression

#6026 chore: Extract CSS instead of injecting
  lib/DirectEditing/TextDirectEditor.php
  lib/Listeners/FilesLoadAdditionalScriptsListener.php
  lib/Listeners/FilesSharingLoadAdditionalScriptsListener.php
  lib/Listeners/LoadEditorListener.php
  lib/Listeners/LoadViewerListener.php
  vite.config.ts
Labels: 3. to review

#6042 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6054 fix(sync): reuse open connection
  cypress/e2e/sync.spec.js
  src/services/SyncService.js
Labels: bug, 4. to release, backport-request

#6058 ci: Fix dep5 for css files
  .reuse/dep5
Labels: tests, 3. to review

#6046 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6047 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6048 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6044 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6060 fix(cy): adjust share test to api change
  cypress/e2e/share.spec.js
Labels: tests, 4. to release

#4585 feat: Use notify push for sync messages during editing
  lib/Service/ApiService.php
  lib/Service/ConfigService.php
  lib/Service/InitialStateProvider.php
  package-lock.json
  package.json
  src/services/NotifyService.js
  src/services/PollingBackend.js
  src/services/WebSocketPolyfill.js
  tests/stub.php
Labels: enhancement, 3. to review, performance 🚀

#6043 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6045 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6071 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6068 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6072 test(cy): Install assistant app version matching the server branch
  .github/workflows/cypress-e2e.yml
Labels: tests, 3. to review, backport-request

#6066 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6067 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6069 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6070 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6038 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
Labels: dependencies, 3. to review, automated

#6052 Feat/search highlight improvements
  src/extensions/Search.js
  src/plugins/searchDecorations.js
  src/plugins/searchQuery.js
  src/tests/plugins/searchDecorations.spec.js
  src/tests/plugins/searchQuery.spec.js
Labels: enhancement, 3. to review, javascript, 🍂 2024-Autumn

#6082 test(cypress): Downgrade to last cypress version that doesn't crash
  cypress/e2e/SmartPicker.spec.js
  package-lock.json
  package.json
Labels: tests, 3. to review, backport-request

#6098 fix: Remove superfluous import
  src/components/Editor/Wrapper.vue
Labels: 3. to review, backport-request

#6079 fix(Assistant): Migrate to new task processing API
  cypress/e2e/Assistant.spec.js
  lib/Service/InitialStateProvider.php
  src/components/Assistant.vue
Labels: 3. to review

#6122 fix(css): Use single quotes
  src/css/prosemirror.scss
Labels: 3. to review

#6123 fix(search): Add data attribute to search decoration
  src/plugins/searchDecorations.js
Labels: 3. to review

#6143 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6142 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6144 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#6148 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6147 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6146 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6150 fix(css): spacing issue in table
  src/css/prosemirror.scss
  src/nodes/Table/TableCellView.vue
  src/nodes/Table/TableHeaderView.vue
Labels: bug, 4. to release

#6155 [stable29] fix: Avoid throwing exceptions during propfind
  lib/DAV/WorkspacePlugin.php
Labels: bug, 3. to review
