Repository nextcloud/text, pull requests merged in 2024-02, with the labels that each got.

#5327 fix: Only unpause focus traps that we paused ourselves
  src/extensions/FocusTrap.js
Labels: bug, 3. to review

#5348 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5349 test(cy): use more robust selectors in file picker
  cypress/e2e/attachments.spec.js
  cypress/e2e/workspace.spec.js
Labels: backport-request

#5357 test(markdownit): separate directory for markdowit tests
  src/tests/markdown.spec.js
  src/tests/markdownit.spec.js
  src/tests/markdownit/bulletList.spec.js
  src/tests/markdownit/callouts.spec.js
  src/tests/markdownit/commonmark.spec.js
  src/tests/markdownit/imageFigures.spec.js
  src/tests/markdownit/mentions.spec.js
  src/tests/markdownit/stripIndent.js
  src/tests/markdownit/taskLists.spec.js
Labels: backport-request

#5360 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#5335 fix: only register workspace once
  cypress/e2e/workspace.spec.js
  src/files.js
Labels: backport-request

#5347 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5370 Bump NcVue to `v8.6.2`
  cypress/e2e/nodes/Table.spec.js
  cypress/e2e/versions.spec.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: 4. to release

#5362 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
Labels: dependencies, 3. to review, automated

#5369 [stable28] bump ncvue to v8.6.2
  cypress/e2e/nodes/Table.spec.js
  cypress/e2e/versions.spec.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/components/Menu/ActionInsertLink.vue
Labels: 3. to review

#5380 fix(ci): use output rather than failure
  .github/workflows/update-node-dist.yml
Labels: 3. to review, integration

#5374 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5375 [main] Fix npm audit
  .github/workflows/npm-audit-fix.yml
  package-lock.json
Labels: dependencies, 3. to review

#5376 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5390 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5393 fix: Add alt attribute to image nodes
  src/nodes/ImageView.vue
Labels: bug, 3. to review, backport-request

#5313 Add interactive flag to reference widgets
  src/css/prosemirror.scss
  src/nodes/Paragraph.js
  src/nodes/ParagraphView.vue
  src/tests/nodes/Table.spec.js
  src/tests/tiptap.spec.js
Labels: enhancement, 3. to review

#5401 fix(link): Don't rewrite links with fileId inside Collectives
  src/helpers/links.js
  src/tests/helpers/links.spec.js
Labels: bug, 3. to review

#5400 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#5395 Feat/4750 Make code type fields copyable
  cypress/e2e/nodes/CodeBlock.spec.js
  src/mixins/CopyToClipboardMixin.js
  src/nodes/CodeBlockView.vue
Labels: enhancement, 2. developing

#5402 fix(viewer): share Vue constructor from Viewer
  src/ViewerVue.js
  src/components/ViewerComponent.vue
  src/extensions/LinkBubblePluginView.js
Labels: 3. to review

#5406 [stable28] fix: apply config flag for accessible features
  lib/Service/ConfigService.php
Labels: bug, 3. to review

#5413 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5418 test(cypress): Force-click breadcrumbs at filelist reload (might be hidden)
  cypress/support/commands.js
Labels: tests, 3. to review, bug: regression

#5412 fix(links): Insert `/f/<fileId>` format for links to files
  cypress/e2e/nodes/Links.spec.js
  cypress/e2e/workspace.spec.js
  cypress/support/commands.js
  src/components/Link/LinkBubbleView.vue
  src/components/Menu/ActionInsertLink.vue
  src/helpers/files.js
  src/helpers/links.js
  src/nodes/ParagraphView.vue
  src/tests/helpers/links.spec.js
Labels: bug, 3. to review

#5269 feat: handle assistant sync task
  .github/workflows/cypress.yml
  cypress/e2e/Assistant.spec.js
  cypress/entrypoint.sh
  lib/AppInfo/Application.php
  lib/Listeners/BeforeAssistantNotificationListener.php
  src/components/Assistant.vue
  tests/stub.php
Labels: enhancement, 3. to review
