Repository nextcloud/text, pull requests merged in 2024-06, with the labels that each got.

#5852 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5851 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5853 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5856 fix(table): Fix readonly detection in vue components
  src/nodes/Table/TableCellView.vue
  src/nodes/Table/TableHeaderView.vue
  src/nodes/Table/TableView.vue
Labels: 3. to review

#5859 test(cypress): Fix selector for new button in files app
  cypress/support/commands.js
Labels: tests, bug: regression

#5854 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5863 fix(locks): only lock when editing
  lib/Service/ApiService.php
Labels: bug, 3. to review

#5880 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5882 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5881 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5883 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5885 chore(deps): update braces to fix security issue
  package-lock.json
Labels: bug

#5886 perf: Lazy load optional dependencies
  src/nodes/CodeBlockView.vue
  vite.config.ts
Labels: enhancement, 3. to review, performance 🚀

#5887 Reset all sessions (in occ command and on upgrade)
  lib/Command/ResetDocument.php
  lib/Migration/ResetSessionsBeforeYjs.php
Labels: bug, 3. to review, feature: sync, 28 feedback

#5817 Content search highlighting
  src/extensions/RichText.js
  src/extensions/Search.js
  src/plugins/searchDecorations.js
  src/plugins/searchQuery.js
  src/tests/plugins/searchDecorations.spec.js
  src/tests/plugins/searchQuery.spec.js
Labels: enhancement, 3. to review, discuss, feedback-requested

#5894 feat(link): Add input rule to insert links using markdown syntax
  src/components/HelpModal.vue
  src/marks/Link.js
Labels: 3. to review

#5895 fix: Ignore pushes of update steps for read only sessions
  lib/Service/DocumentService.php
  lib/YjsMessage.php
Labels: bug, 3. to review

#5910 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5916 Add REUSE badge
  .github/pull_request_template.md
  .github/pull_request_template.md.license
  README.md
Labels: 4. to release, technical debt

#5918 Truncate tables and rename documents folder on reset
  lib/Command/ResetDocument.php
  lib/Cron/Cleanup.php
  lib/Db/DocumentMapper.php
  lib/Db/SessionMapper.php
  lib/Db/StepMapper.php
  lib/Migration/ResetSessionsBeforeYjs.php
  lib/Service/DocumentService.php
  lib/Service/SessionService.php
  tests/unit/Service/DocumentServiceTest.php
Labels: 2. developing, backport-request, bug: regression

#5846 fix(SmartPicker): Insert smart picker links as preview per default
  cypress/e2e/nodes/Preview.spec.js
  src/components/Menu/ActionInsertLink.vue
  src/components/Suggestion/LinkPicker/suggestions.js
  src/nodes/Preview.js
Labels: enhancement, 3. to review, backport-request

#5927 fix(Preview): Show reference fallback
  src/nodes/Preview.vue
Labels: 3. to review, backport-request, bug: regression

#5929 fix(menu): Use paperclip icon for inserting attachments menu item
  src/components/Menu/ActionEntry.scss
  src/components/Menu/entries.js
  src/components/icons.js
Labels: 3. to review

#5933 perf: Use getFirstNodeById and pass userId for our internal helper to avoid fetching mountpoints
  lib/DAV/WorkspacePlugin.php
  lib/Middleware/SessionMiddleware.php
  lib/Notification/Notifier.php
  lib/Service/ApiService.php
  lib/Service/AttachmentService.php
  lib/Service/DocumentService.php
Labels: 3. to review, performance 🚀

#5930 perf: Reduce polling interval for read only users
  src/services/PollingBackend.js
Labels: 3. to review, performance 🚀

#5937 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5926 fix(LinkPicker): Fix inserting markdown (e.g. from `text_templates` app)
  src/components/Suggestion/LinkPicker/suggestions.js
Labels: 3. to review, backport-request, bug: regression

#5924 fix(LinkBubble): Don't open bubble at initialization and on remote changes
  cypress/e2e/initial.spec.js
  cypress/e2e/workspace.spec.js
  src/components/Link/LinkBubbleView.vue
  src/plugins/LinkBubblePluginView.js
  src/plugins/links.js
Labels: 3. to review, backport-request

#5914 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5911 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5913 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5915 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#5948 perf: Cache workspace content for propfinds
  lib/DAV/WorkspacePlugin.php
Labels: 3. to review, performance 🚀

#5952 ci: Skip cypress test crashing electron right now
  cypress/e2e/SmartPicker.spec.js
Labels: tests, 3. to review, backport-request

#5961 perf: get folder node directly from dav node instead of getting it by id
  lib/DAV/WorkspacePlugin.php
Labels: 3. to review, performance 🚀

#5959 perf: optimize WorkspaceService::getFile
  lib/Service/WorkspaceService.php
Labels: 4. to release, performance 🚀

#5975 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
