Repository nextcloud/text, pull requests merged in 2024-05, with the labels that each got.

#5727 test(cy): rely on @nextcloud/axios for requests
  cypress/e2e/api/SessionApi.spec.js
  cypress/e2e/api/SyncServiceProvider.spec.js
  cypress/e2e/api/UsersApi.spec.js
  cypress/e2e/directediting.spec.js
  cypress/e2e/propfind.spec.js
  cypress/support/commands.js
  cypress/support/sessions.js
Labels: tests, 3. to review

#5750 fix(editor): requestAnimationFrame in onResize callbacks
  src/components/Editor.vue
  src/components/Editor/EditorOutline.vue
  src/components/Menu/MenuBar.vue
Labels: backport-request

#5771 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5717 perf(bootstrap): Lazy register template creator through event
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/AppInfo/Application.php
  lib/Listeners/RegisterTemplateCreatorListener.php
Labels: enhancement, 3. to review, performance 🚀

#5772 test(cypress): Avoid failure when editor is updated on webdav requests
  cypress/e2e/propfind.spec.js
Labels: tests, 3. to review

#5795 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5793 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5794 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5796 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5799 feat(editor): Add keyboard shortcut (Ctrl-Alt-H) to toggle outline
  src/components/Editor/EditorOutline.vue
  src/components/Editor/Wrapper.vue
  src/components/HelpModal.vue
Labels: bug, enhancement, 3. to review

#5367 feat: Move to vite for bundling
  .eslintrc.cjs
  .eslintrc.js
  .github/workflows/cypress-e2e.yml
  .stylelintrc.cjs
  .tsconfig.json
  babel.config.cjs
  cypress.config.mjs
  cypress/e2e/attachments.spec.js
  cypress/e2e/nodes/ListItem.spec.js
  cypress/e2e/nodes/Preview.spec.js
  cypress/e2e/nodes/Table.spec.js
  cypress/support/commands.js
  jest-raw-loader.cjs
  package-lock.json
  package.json
  src/EditorFactory.js
  src/css/print.scss
  src/editor.js
  src/files.js
  src/helpers/base64.ts
  src/helpers/yjs.js
  src/init.js
  src/main.js
  src/package.js
  src/public.js
  src/services/WebSocketPolyfill.js
  src/tests/setup.mjs
  src/tests/yjs.spec.js
  src/viewer.js
  vite.config.js
  vite.config.ts
  webpack.config.js
Labels: 3. to review, performance 🚀

#5815 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5830 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5831 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#5833 fix(PreviewOptions): Set buttons position to absolute
  src/components/Editor/PreviewOptions.vue
Labels: 3. to review, bug: regression

#5802 fix: showing folder description on favorites
  src/helpers/files.js
Labels: bug, 3. to review
