Repository nextcloud/text, pull requests merged in 2025-07, with the labels that each got.

#7364 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7383 [stable30] Fixed issue nextcloud/notes/#1538
  src/services/WebdavClient.ts
Labels: 3. to review

#7389 Revert "debug(SessionMiddleware): Log if we have an invalid session"
  lib/Middleware/SessionMiddleware.php
Labels: backport-request

#7409 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7417 chore(refactor): save service with new connection
  cypress/e2e/sync.spec.js
  cypress/support/sessions.js
  src/apis/Connect.ts
  src/apis/Save.ts
  src/apis/Sync.ts
  src/components/Editor.vue
  src/composables/useSaveService.ts
  src/services/SaveService.ts
  src/services/SessionConnection.js
Labels: 3. to review, technical debt

#7418 fix(files): workspace implementation
  src/helpers/files.js
  src/views/RichWorkspace.vue
Labels: 3. to review, technical debt

#7408 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7410 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7434 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7470 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7500 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7499 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7501 fix(workspace): toggle right away and only render if needed
  src/helpers/files.js
  src/views/RichWorkspace.vue
Labels: backport-request

#7477 fix(share): use relative path in share as davPath for attachments
  cypress/e2e/attachments.spec.js
  cypress/e2e/shareWithAttachments.spec.js
  lib/Service/AttachmentService.php
Labels: backport-request

#7509 Fixes for TextDirection extension
  package-lock.json
  package.json
  src/css/prosemirror.scss
  src/extensions/RichText.js
  src/extensions/TextDirection.ts
  src/nodes/Callout.vue
  src/tests/tiptap.spec.js
Labels: bug, 3. to review, backport-request

#7513 Further TextDirection improvements
  src/extensions/Keymap.js
  src/extensions/RichText.js
  src/extensions/TextDirection.ts
  src/nodes/Callout.vue
  src/nodes/DetailsView.vue
  src/nodes/Table/TableCellView.vue
  src/nodes/Table/TableHeaderView.vue
  src/tests/fixtures/tables/handbook/handbook.html
  src/tests/fixtures/tables/handbook/handbook.out.html
  src/tests/nodes/Table.spec.js
Labels: bug, 3. to review, backport-request
