Repository nextcloud/text, pull requests merged in 2025-10, with the labels that each got.

#7714 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7713 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7715 [stable32] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7718 fix(css): Adjust status icon colors to Nextcloud 32 variable names
  src/components/Assistant.vue
  src/nodes/Callout.vue
Labels: bug, 3. to review, backport-request, papercut, regression, ux

#7722 [stable31] test(cy): Test against server stable31 on stable31
  .github/workflows/cypress-e2e.yml
Labels: tests, 3. to review

#7723 fix(ci): Always use main branch for assistant app
  .github/workflows/cypress-e2e.yml
Labels: tests, 3. to review

#7719 Replace cypress component tests
  .github/workflows/cypress-component.yml
  cypress/component/editor/search.cy.js
  src/declarations.d.ts
  src/extensions/RichText.js
  src/extensions/Search.ts
  src/helpers/base64.ts
  src/helpers/yjs.ts
  src/plugins/searchDecorations.js
  src/services/Outbox.ts
  src/services/SyncService.ts
  src/tests/extensions/Search.spec.ts
  src/tests/fixtures/lorem.txt
  src/tests/helpers/yjs.spec.ts
  src/tests/upstream/yjs.spec.ts
Labels: backport-request

#7729 fix(print): Overwrite `display: grid` to prevent cut content
  src/css/print.scss
Labels: bug, 3. to review, backport-request, feature: printing

#7742 fix(sync): Only send recovery step in case of SyncStep1
  src/services/WebSocketPolyfill.ts
Labels: bug, feature: sync
