Repository nextcloud/text, pull requests merged in 2025-06, with the labels that each got.

#7278 ci: update node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#7295 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7315 fix: prevent loading the code block extension twice for plain text
  src/EditorFactory.js
  src/extensions/PlainText.js
Labels: bug, 3. to review

#7197 fix(files): Add smooth animation via clicking on heading
  src/components/Editor/TableOfContents.vue
  src/css/prosemirror.scss
  src/plugins/headingAnchor.js
Labels: bug, 3. to review, backport-request

#7074 refactor: cleanup main entry point
  src/main.js
  src/viewer.js
Labels: 3. to review, technical debt

#7343 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7082 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#7365 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7366 [stable31] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: dependencies, 3. to review

#7368 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#7372 debug(SessionMiddleware): Log if we have an invalid session
  lib/Middleware/SessionMiddleware.php
Labels: 3. to review
