Repository nextcloud/text, pull requests merged in 2025-03, with the labels that each got.

#6926 Help modal improvements
  src/components/HelpModal.vue
  src/components/Menu/keys.js
  src/components/Suggestion/Mention/suggestions.js
Labels: bug, 3. to review

#6924 chore(deps): upgrade vite to version 6
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#6930 drop/vuex
  package-lock.json
  package.json
  src/components/Editor/EditorOutline.vue
  src/components/Editor/TableOfContents.vue
  src/components/Editor/Wrapper.vue
  src/components/Menu/ActionList.vue
  src/components/Menu/BaseActionEntry.js
  src/editor.js
  src/files.js
  src/helpers/files.js
  src/main.js
  src/mixins/store.js
  src/nodes/Heading.js
  src/nodes/ImageView.vue
  src/plugins/extractHeadings.js
  src/public.js
  src/services/AttachmentResolver.js
  src/store/index.js
  src/store/mutation-types.js
  src/store/plugin.js
  src/tests/components/Editor/TableOfContents.spec.js
  src/tests/plugins/extractHeadings.spec.js
  src/tests/setup.mjs
  src/tests/testHelpers/nextcloudMocks.js
  src/tests/testHelpers/vueMocks.js
Labels: bug, 3. to review

#6922 fix: Skip notifications for self mentions
  lib/Service/NotificationService.php
Labels: bug, 3. to review

#6567 fix: replace deprecated translation methods
  lib/Service/InitialStateProvider.php
  src/components/Assistant.vue
  src/components/Menu/MenuBar.vue
  src/components/Modal/Translate.vue
Labels: bug, 3. to review, backport-request

#6903 Keep layout on sync errors
  .github/workflows/cypress-e2e.yml
  cypress/e2e/nodes/CodeBlock.spec.js
  cypress/snapshots/base/cypress/e2e/print.spec.js/print view in single-file share.png
  cypress/snapshots/base/cypress/e2e/print.spec.js/print view in viewer.png
  src/components/CollisionResolveDialog.vue
  src/components/Editor.vue
  src/components/Editor/DocumentStatus.vue
  src/components/Editor/DocumentStatus/SyncStatus.vue
  src/components/Editor/Wrapper.vue
  src/components/ViewerComponent.vue
  src/tests/components/SyncStatus.spec.js
  src/tests/components/__snapshots__/SyncStatus.spec.js.snap
Labels: bug, backport-request

#6947 update(workflow): block-merge-freeze to latest
  .github/workflows/block-merge-freeze.yml
Labels: 3. to review

#6918 fix: resolve file version conflict during restore
  lib/AppInfo/Application.php
Labels: 3. to review, feature: conflict resolution, ux, feedback-requested

#6937 fix: Avoid pushing empty messages
  lib/Service/ApiService.php
Labels: bug, 3. to review, backport-request, log finding

#6960 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6965 Fix flaky cypress tests
  cypress/e2e/Assistant.spec.js
  cypress/e2e/api/SessionApi.spec.js
Labels: tests, 3. to review, backport-request

#6964 fix(ui): style conflict resolution buttons
  cypress/e2e/conflict.spec.js
  cypress/e2e/sync.spec.js
  src/components/CollisionResolveDialog.vue
  src/components/Editor.vue
  src/components/Editor/DocumentStatus.vue
  src/components/Editor/DocumentStatus/SyncStatus.vue
  src/tests/components/__snapshots__/SyncStatus.spec.js.snap
Labels: design, 3. to review, backport-request, ux

#6891 fix(workspace): Use filecache existance for checking if readme exists
  lib/DAV/WorkspacePlugin.php
  lib/Service/WorkspaceService.php
Labels: 3. to review, performance 🚀

#5690 remove old link when editing
  cypress/e2e/Links.spec.js
  cypress/e2e/marks/Link.spec.js
  src/components/Menu/ActionInsertLink.vue
  src/marks/Link.js
  src/tests/marks/Link.spec.js
  src/tests/marks/__snapshots__/Link.spec.js.snap
Labels: bug, 2. developing

#6979 [stable29] chore: Downgrade @nextcloud/webpack-vue-config
  package-lock.json
  package.json
Labels: dependencies

#6856 fix(files): create suggestions bar
  src/components/Editor.vue
  src/components/Menu/ActionInsertLink.vue
  src/components/SuggestionsBar.vue
  src/css/print.scss
  src/css/prosemirror.scss
  src/helpers/filePicker.js
Labels: enhancement, 3. to review

#6983 fix(files): Place menubar at the bottom on mobile
  cypress/snapshots/base/cypress/e2e/print.spec.js/print view in single-file share.png
  cypress/snapshots/base/cypress/e2e/print.spec.js/print view in viewer.png
  src/components/Editor/ContentContainer.vue
  src/components/Editor/MediaHandler.vue
  src/components/Menu/MenuBar.vue
  src/components/SuggestionsBar.vue
Labels: 3. to review

#7025 Hide emoji button from the menubar on mobile
  src/components/Menu/entries.js
Labels: 2. developing
