Repository nextcloud/text, pull requests merged in 2025-08, with the labels that each got.

#7533 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#7534 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#7531 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7540 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7542 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#7537 feat(files): add drag handler for nodes
  cypress/e2e/MenuBar.spec.js
  cypress/snapshots/base/cypress/e2e/print.spec.js/print view in single-file share.png
  cypress/snapshots/base/cypress/e2e/print.spec.js/print view in viewer.png
  package-lock.json
  package.json
  src/components/Editor/ContentContainer.vue
  src/components/Editor/MediaHandler.vue
  src/components/Editor/SmartPickerMenu.vue
  src/composables/useEditorWidth.ts
  src/css/print.scss
  src/css/prosemirror.scss
  src/extensions/RichText.js
Labels: 3. to review

#7575 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7577 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#7581 build: update node and npm engines versions
  package.json
Labels: dependencies

#7584 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
