Repository nextcloud/text, pull requests merged in 2025-05, with the labels that each got.

#6676 feat(attachments): add support for creating new attachments
  appinfo/routes.php
  cypress/e2e/attachments.spec.js
  lib/Controller/AttachmentController.php
  lib/Service/AttachmentService.php
  src/components/Editor/MediaHandler.provider.js
  src/components/Editor/MediaHandler.vue
  src/components/Menu/ActionAttachmentUpload.vue
  src/components/icons.js
  src/services/SessionApi.js
  src/services/SyncService.js
  tests/unit/Service/AttachmentServiceTest.php
Labels: enhancement, 3. to review, feedback-requested

#7157 fix(files): Remove obsolete loading code from old API, add public shared id to enabled view
  lib/Listeners/FilesSharingLoadAdditionalScriptsListener.php
  src/helpers/files.js
  src/public.js
Labels: bug, 3. to review, backport-request

#7132 feat: view E2EE files
  src/components/ViewerComponent.vue
  src/helpers/mime.js
Labels: enhancement, 3. to review

#7154 Disable attachment upload on federated shares
  lib/Service/ApiService.php
  src/components/Menu/ActionAttachmentUpload.vue
  src/components/SuggestionsBar.vue
  src/services/SessionApi.js
  src/services/SyncService.js
  src/tests/services/SessionApi.spec.js
  src/tests/services/SyncService.spec.js
  tests/unit/Service/ApiServiceTest.php
Labels: 3. to review, backport-request

#7184 chore(SessionList): Migrate to NcButton and MDI icon
  src/components/Editor/SessionList.vue
Labels: design, 3. to review, backport-request, technical debt

#7185 fix: Adjust padding in table cell and header components
  src/css/prosemirror.scss
  src/nodes/Table/TableCellView.vue
  src/nodes/Table/TableHeaderView.vue
Labels: bug

#7188 feat(link): Toggle link on selection with Mod-K shortcut
  src/components/HelpModal.vue
  src/components/Link/LinkBubbleView.vue
  src/components/Menu/entries.js
  src/marks/Link.js
Labels: enhancement, 3. to review, backport-request

#7201 fix(image): Only focus image description on newly inserted image
  src/components/Editor/MediaHandler.vue
  src/nodes/ImageView.vue
Labels: bug, 2. developing, regression

#7209 feature: Delay image load until visible
  src/nodes/ImageView.vue
Labels: bug, 4. to release

#7202 fix(details): Accept details open tag and summary tag in same line
  src/markdownit/details.ts
  src/tests/markdownit/details.spec.js
Labels: bug, 3. to review, backport-request

#7199 [stable29] fix submit button on file picker dialog
  src/components/Menu/ActionInsertLink.vue
Labels: bug, 4. to release

#6923 feat: Implement event so collectives can inject custom notification messages
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/Event/MentionEvent.php
  lib/Notification/Notifier.php
Labels: enhancement, 3. to review

#7229 Respect default extension setting in direct editing
  composer/autoload.php
  composer/composer/InstalledVersions.php
  lib/DirectEditing/TextDirectEditor.php
  lib/DirectEditing/TextDocumentCreator.php
  tests/unit/DirectEditing/TextDocumentCreatorTest.php
Labels: bug, 3. to review

#7237 fix(attachments): Adjust path to attachments folder when copying a node
  lib/Listeners/NodeCopiedListener.php
  lib/Service/AttachmentService.php
  tests/unit/Service/AttachmentServiceTest.php
Labels: bug, 3. to review, backport-request
