Repository nextcloud/text, pull requests merged in 2025-02, with the labels that each got.

#6889 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#6674 feat(editor): add "Open in new tab" option for link previews
  src/components/Editor/PreviewOptions.vue
  src/plugins/extractLinkParagraphs.js
  src/tests/plugins/extractLinkParagraphs.spec.js
Labels: enhancement, 3. to review, ux, feedback-requested

#6836 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#6898 fix/use e2e test server
  cypress.config.mjs
  cypress/e2e/openreadonly.spec.js
  cypress/e2e/print.spec.js
  cypress/support/commands.js
  cypress/utils/index.js
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#6874 fix(files): add `tiptap-text-direction` extension to support RTL
  package-lock.json
  package.json
  src/css/prosemirror.scss
  src/extensions/RichText.js
  src/tests/tiptap.spec.js
Labels: 3. to review, backport-request

#6915 fix/6871 smart add to next line
  src/plugins/currentLineMenu.js
  vite.config.ts
Labels: design, feature: formatting, 3. to review, ux, skill: frontend

#6919 ci: Add codecov config
  REUSE.toml
  codecov.yml
Labels: tests, 3. to review

#6912 [main] Fix npm audit
  package-lock.json
  package.json
Labels: dependencies, 3. to review
