Repository nextcloud/text, pull requests merged in 2025-09, with the labels that each got.

#7599 fix(links): do not steal focus on initial loading
  src/components/Link/LinkBubbleView.vue
Labels: backport-request

#7605 Migrate to outline Material Symbol style
  src/components/Assistant.vue
  src/components/Editor/OfflineState.vue
  src/components/Editor/PreviewOptions.vue
  src/components/icons.js
  src/nodes/CodeBlock/CodeBlockView.vue
  src/nodes/ImageView.vue
  src/nodes/Table/TableCellView.vue
  src/nodes/Table/TableHeaderView.vue
  src/nodes/Table/TableView.vue
Labels: design, 3. to review

#7616 [stable32] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: dependencies, 3. to review

#7639 [stable32] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7622 feat: use new assistant theme
  src/components/Assistant.vue
Labels: enhancement, 3. to review

#7647 docs: Document how to test a direct editing session in the browser
  README.md
Labels: 3. to review, documentation

#7560 fix(readonly-bar): Clean up read-only menu bar to behave consistently with normal menu bar
  cypress/e2e/openreadonly.spec.js
  cypress/e2e/share.spec.js
  src/components/Editor.vue
  src/components/Menu/ReadonlyBar.vue
Labels: backport-request, feedback-requested

#7666 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7669 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7672 fix(print): hide readonly bar in print view
  src/css/print.scss
Labels: bug, 3. to review, backport-request, regression

#7668 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#7695 chore(DocumentService): Raise log level for SyncStep2 message to error
  lib/Service/DocumentService.php
Labels: 3. to review, feature: sync
